( GMP Wrapper 0.0.0 )

\ This file has been generated using SWIG and fsi,
\ and is already platform dependent, search for the corresponding
\ fsi-file to compile it where no one has compiled it before ;)
\ Forth systems have their own own dynamic loader and don't need addional C-Code.
\ That's why this file will just print normal forth-code once compiled
\ and can be used directly with include or require.
\ As all comments are stripped during the compilation, please
\ insert the copyright notice of the original file here.

\ ----===< prefix >===-----
c-library gmp
s" gmp" add-lib
\c #include <gmp.h>

\ ----===< int constants >===-----
#1	constant _GMP_H_HAVE_FILE
#0	constant __GMP_HAVE_HOST_CPU_FAMILY_power
#0	constant __GMP_HAVE_HOST_CPU_FAMILY_powerpc
#64	constant GMP_LIMB_BITS
#0	constant GMP_NAIL_BITS
#64	constant GMP_NUMB_BITS
#6	constant __GNU_MP__
#0	constant __GMP_LIBGMP_DLL
#0	constant __GMP_MP_SIZE_T_INT
#1	constant __GMP_INLINE_PROTOTYPES
#6	constant __GNU_MP_VERSION
#2	constant __GNU_MP_VERSION_MINOR
#0	constant __GNU_MP_VERSION_PATCHLEVEL
#60200	constant __GNU_MP_RELEASE

\ --------===< enums >===---------
#0	constant GMP_RAND_ALG_DEFAULT
#0	constant GMP_RAND_ALG_LC
#0	constant GMP_ERROR_NONE
#1	constant GMP_ERROR_UNSUPPORTED_ARGUMENT
#2	constant GMP_ERROR_DIVISION_BY_ZERO
#4	constant GMP_ERROR_SQRT_OF_NEGATIVE
#8	constant GMP_ERROR_INVALID_ARGUMENT

\ -------===< structs >===--------
\ __mpz_struct
begin-structure __mpz_struct
	drop 0 4 +field __mpz_struct-_mp_alloc
	drop 4 4 +field __mpz_struct-_mp_size
	drop 8 8 +field __mpz_struct-_mp_d
drop 16 end-structure
\ __mpq_struct
begin-structure __mpq_struct
	drop 0 16 +field __mpq_struct-_mp_num
	drop 16 16 +field __mpq_struct-_mp_den
drop 32 end-structure
\ __mpf_struct
begin-structure __mpf_struct
	drop 0 4 +field __mpf_struct-_mp_prec
	drop 4 4 +field __mpf_struct-_mp_size
	drop 16 8 +field __mpf_struct-_mp_d
	drop 8 8 +field __mpf_struct-_mp_exp
drop 24 end-structure
\ __gmp_randstate_struct
begin-structure __gmp_randstate_struct
	drop 0 16 +field __gmp_randstate_struct-_mp_seed
	drop 16 4 +field __gmp_randstate_struct-_mp_alg
	drop 24 8 +field __gmp_randstate_struct-_mp_algdata
drop 32 end-structure
\ __gmp_randstate_struct__mp_algdata
begin-structure __gmp_randstate_struct__mp_algdata
	drop 0 8 +field __gmp_randstate_struct__mp_algdata-_mp_lc
drop 8 end-structure

\ ------===< functions >===-------
c-function __gmp_set_memory_functions __gmp_set_memory_functions a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmp_get_memory_functions __gmp_get_memory_functions a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmp_randinit __gmp_randinit a n ... -- void	( <noname> <noname> <noname> -- )
c-function __gmp_randinit_default __gmp_randinit_default a -- void	( <noname> -- )
c-function __gmp_randinit_lc_2exp __gmp_randinit_lc_2exp a a u u -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmp_randinit_lc_2exp_size __gmp_randinit_lc_2exp_size a u -- n	( <noname> <noname> -- )
c-function __gmp_randinit_mt __gmp_randinit_mt a -- void	( <noname> -- )
c-function __gmp_randinit_set __gmp_randinit_set a a -- void	( <noname> <noname> -- )
c-function __gmp_randseed __gmp_randseed a a -- void	( <noname> <noname> -- )
c-function __gmp_randseed_ui __gmp_randseed_ui a u -- void	( <noname> <noname> -- )
c-function __gmp_randclear __gmp_randclear a -- void	( <noname> -- )
c-function __gmp_urandomb_ui __gmp_urandomb_ui a u -- u	( <noname> <noname> -- )
c-function __gmp_urandomm_ui __gmp_urandomm_ui a u -- u	( <noname> <noname> -- )
c-function __gmp_asprintf __gmp_asprintf a s ... -- n	( <noname> <noname> <noname> -- )
c-function __gmp_fprintf __gmp_fprintf a s ... -- n	( <noname> <noname> <noname> -- )
c-function __gmp_printf __gmp_printf s ... -- n	( <noname> <noname> -- )
c-function __gmp_snprintf __gmp_snprintf a n s ... -- n	( <noname> <noname> <noname> <noname> -- )
c-function __gmp_sprintf __gmp_sprintf a s ... -- n	( <noname> <noname> <noname> -- )
c-function __gmp_fscanf __gmp_fscanf a s ... -- n	( <noname> <noname> <noname> -- )
c-function __gmp_scanf __gmp_scanf s ... -- n	( <noname> <noname> -- )
c-function __gmp_sscanf __gmp_sscanf s s ... -- n	( <noname> <noname> <noname> -- )
c-function __gmpz_realloc __gmpz_realloc a n -- a	( <noname> <noname> -- )
c-function __gmpz_abs __gmpz_abs a a -- void	( <noname> <noname> -- )
c-function __gmpz_add __gmpz_add a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_add_ui __gmpz_add_ui a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_addmul __gmpz_addmul a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_addmul_ui __gmpz_addmul_ui a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_and __gmpz_and a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_array_init __gmpz_array_init a n n -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_bin_ui __gmpz_bin_ui a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_bin_uiui __gmpz_bin_uiui a u u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_cdiv_q __gmpz_cdiv_q a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_cdiv_q_2exp __gmpz_cdiv_q_2exp a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_cdiv_q_ui __gmpz_cdiv_q_ui a a u -- u	( <noname> <noname> <noname> -- )
c-function __gmpz_cdiv_qr __gmpz_cdiv_qr a a a a -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpz_cdiv_qr_ui __gmpz_cdiv_qr_ui a a a u -- u	( <noname> <noname> <noname> <noname> -- )
c-function __gmpz_cdiv_r __gmpz_cdiv_r a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_cdiv_r_2exp __gmpz_cdiv_r_2exp a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_cdiv_r_ui __gmpz_cdiv_r_ui a a u -- u	( <noname> <noname> <noname> -- )
c-function __gmpz_cdiv_ui __gmpz_cdiv_ui a u -- u	( <noname> <noname> -- )
c-function __gmpz_clear __gmpz_clear a -- void	( <noname> -- )
c-function __gmpz_clears __gmpz_clears a ... -- void	( <noname> <noname> -- )
c-function __gmpz_clrbit __gmpz_clrbit a u -- void	( <noname> <noname> -- )
c-function __gmpz_cmp __gmpz_cmp a a -- n	( <noname> <noname> -- )
c-function __gmpz_cmp_d __gmpz_cmp_d a r -- n	( <noname> <noname> -- )
c-function __gmpz_cmp_si __gmpz_cmp_si a n -- n	( <noname> <noname> -- )
c-function __gmpz_cmp_ui __gmpz_cmp_ui a u -- n	( <noname> <noname> -- )
c-function __gmpz_cmpabs __gmpz_cmpabs a a -- n	( <noname> <noname> -- )
c-function __gmpz_cmpabs_d __gmpz_cmpabs_d a r -- n	( <noname> <noname> -- )
c-function __gmpz_cmpabs_ui __gmpz_cmpabs_ui a u -- n	( <noname> <noname> -- )
c-function __gmpz_com __gmpz_com a a -- void	( <noname> <noname> -- )
c-function __gmpz_combit __gmpz_combit a u -- void	( <noname> <noname> -- )
c-function __gmpz_congruent_p __gmpz_congruent_p a a a -- n	( <noname> <noname> <noname> -- )
c-function __gmpz_congruent_2exp_p __gmpz_congruent_2exp_p a a u -- n	( <noname> <noname> <noname> -- )
c-function __gmpz_congruent_ui_p __gmpz_congruent_ui_p a u u -- n	( <noname> <noname> <noname> -- )
c-function __gmpz_divexact __gmpz_divexact a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_divexact_ui __gmpz_divexact_ui a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_divisible_p __gmpz_divisible_p a a -- n	( <noname> <noname> -- )
c-function __gmpz_divisible_ui_p __gmpz_divisible_ui_p a u -- n	( <noname> <noname> -- )
c-function __gmpz_divisible_2exp_p __gmpz_divisible_2exp_p a u -- n	( <noname> <noname> -- )
c-function __gmpz_dump __gmpz_dump a -- void	( <noname> -- )
c-function __gmpz_export __gmpz_export a a n n n n a -- a	( <noname> <noname> <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpz_fac_ui __gmpz_fac_ui a u -- void	( <noname> <noname> -- )
c-function __gmpz_2fac_ui __gmpz_2fac_ui a u -- void	( <noname> <noname> -- )
c-function __gmpz_mfac_uiui __gmpz_mfac_uiui a u u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_primorial_ui __gmpz_primorial_ui a u -- void	( <noname> <noname> -- )
c-function __gmpz_fdiv_q __gmpz_fdiv_q a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_fdiv_q_2exp __gmpz_fdiv_q_2exp a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_fdiv_q_ui __gmpz_fdiv_q_ui a a u -- u	( <noname> <noname> <noname> -- )
c-function __gmpz_fdiv_qr __gmpz_fdiv_qr a a a a -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpz_fdiv_qr_ui __gmpz_fdiv_qr_ui a a a u -- u	( <noname> <noname> <noname> <noname> -- )
c-function __gmpz_fdiv_r __gmpz_fdiv_r a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_fdiv_r_2exp __gmpz_fdiv_r_2exp a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_fdiv_r_ui __gmpz_fdiv_r_ui a a u -- u	( <noname> <noname> <noname> -- )
c-function __gmpz_fdiv_ui __gmpz_fdiv_ui a u -- u	( <noname> <noname> -- )
c-function __gmpz_fib_ui __gmpz_fib_ui a u -- void	( <noname> <noname> -- )
c-function __gmpz_fib2_ui __gmpz_fib2_ui a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_fits_sint_p __gmpz_fits_sint_p a -- n	( <noname> -- )
c-function __gmpz_fits_slong_p __gmpz_fits_slong_p a -- n	( <noname> -- )
c-function __gmpz_fits_sshort_p __gmpz_fits_sshort_p a -- n	( <noname> -- )
c-function __gmpz_fits_uint_p __gmpz_fits_uint_p a -- n	( <noname> -- )
c-function __gmpz_fits_ulong_p __gmpz_fits_ulong_p a -- n	( <noname> -- )
c-function __gmpz_fits_ushort_p __gmpz_fits_ushort_p a -- n	( <noname> -- )
c-function __gmpz_gcd __gmpz_gcd a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_gcd_ui __gmpz_gcd_ui a a u -- u	( <noname> <noname> <noname> -- )
c-function __gmpz_gcdext __gmpz_gcdext a a a a a -- void	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpz_get_d __gmpz_get_d a -- r	( <noname> -- )
c-function __gmpz_get_d_2exp __gmpz_get_d_2exp a a -- r	( <noname> <noname> -- )
c-function __gmpz_get_si __gmpz_get_si a -- n	( <noname> -- )
c-function __gmpz_get_str __gmpz_get_str a n a -- a	( <noname> <noname> <noname> -- )
c-function __gmpz_get_ui __gmpz_get_ui a -- u	( <noname> -- )
c-function __gmpz_getlimbn __gmpz_getlimbn a n -- u	( <noname> <noname> -- )
c-function __gmpz_hamdist __gmpz_hamdist a a -- u	( <noname> <noname> -- )
c-function __gmpz_import __gmpz_import a n n n n n a -- void	( <noname> <noname> <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpz_init __gmpz_init a -- void	( <noname> -- )
c-function __gmpz_init2 __gmpz_init2 a u -- void	( <noname> <noname> -- )
c-function __gmpz_inits __gmpz_inits a ... -- void	( <noname> <noname> -- )
c-function __gmpz_init_set __gmpz_init_set a a -- void	( <noname> <noname> -- )
c-function __gmpz_init_set_d __gmpz_init_set_d a r -- void	( <noname> <noname> -- )
c-function __gmpz_init_set_si __gmpz_init_set_si a n -- void	( <noname> <noname> -- )
c-function __gmpz_init_set_str __gmpz_init_set_str a s n -- n	( <noname> <noname> <noname> -- )
c-function __gmpz_init_set_ui __gmpz_init_set_ui a u -- void	( <noname> <noname> -- )
c-function __gmpz_inp_raw __gmpz_inp_raw a a -- n	( <noname> <noname> -- )
c-function __gmpz_inp_str __gmpz_inp_str a a n -- n	( <noname> <noname> <noname> -- )
c-function __gmpz_invert __gmpz_invert a a a -- n	( <noname> <noname> <noname> -- )
c-function __gmpz_ior __gmpz_ior a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_jacobi __gmpz_jacobi a a -- n	( <noname> <noname> -- )
c-function __gmpz_kronecker_si __gmpz_kronecker_si a n -- n	( <noname> <noname> -- )
c-function __gmpz_kronecker_ui __gmpz_kronecker_ui a u -- n	( <noname> <noname> -- )
c-function __gmpz_si_kronecker __gmpz_si_kronecker n a -- n	( <noname> <noname> -- )
c-function __gmpz_ui_kronecker __gmpz_ui_kronecker u a -- n	( <noname> <noname> -- )
c-function __gmpz_lcm __gmpz_lcm a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_lcm_ui __gmpz_lcm_ui a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_lucnum_ui __gmpz_lucnum_ui a u -- void	( <noname> <noname> -- )
c-function __gmpz_lucnum2_ui __gmpz_lucnum2_ui a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_millerrabin __gmpz_millerrabin a n -- n	( <noname> <noname> -- )
c-function __gmpz_mod __gmpz_mod a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_mul __gmpz_mul a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_mul_2exp __gmpz_mul_2exp a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_mul_si __gmpz_mul_si a a n -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_mul_ui __gmpz_mul_ui a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_neg __gmpz_neg a a -- void	( <noname> <noname> -- )
c-function __gmpz_nextprime __gmpz_nextprime a a -- void	( <noname> <noname> -- )
c-function __gmpz_out_raw __gmpz_out_raw a a -- n	( <noname> <noname> -- )
c-function __gmpz_out_str __gmpz_out_str a n a -- n	( <noname> <noname> <noname> -- )
c-function __gmpz_perfect_power_p __gmpz_perfect_power_p a -- n	( <noname> -- )
c-function __gmpz_perfect_square_p __gmpz_perfect_square_p a -- n	( <noname> -- )
c-function __gmpz_popcount __gmpz_popcount a -- u	( <noname> -- )
c-function __gmpz_pow_ui __gmpz_pow_ui a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_powm __gmpz_powm a a a a -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpz_powm_sec __gmpz_powm_sec a a a a -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpz_powm_ui __gmpz_powm_ui a a u a -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpz_probab_prime_p __gmpz_probab_prime_p a n -- n	( <noname> <noname> -- )
c-function __gmpz_random __gmpz_random a n -- void	( <noname> <noname> -- )
c-function __gmpz_random2 __gmpz_random2 a n -- void	( <noname> <noname> -- )
c-function __gmpz_realloc2 __gmpz_realloc2 a u -- void	( <noname> <noname> -- )
c-function __gmpz_remove __gmpz_remove a a a -- u	( <noname> <noname> <noname> -- )
c-function __gmpz_root __gmpz_root a a u -- n	( <noname> <noname> <noname> -- )
c-function __gmpz_rootrem __gmpz_rootrem a a a u -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpz_rrandomb __gmpz_rrandomb a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_scan0 __gmpz_scan0 a u -- u	( <noname> <noname> -- )
c-function __gmpz_scan1 __gmpz_scan1 a u -- u	( <noname> <noname> -- )
c-function __gmpz_set __gmpz_set a a -- void	( <noname> <noname> -- )
c-function __gmpz_set_d __gmpz_set_d a r -- void	( <noname> <noname> -- )
c-function __gmpz_set_f __gmpz_set_f a a -- void	( <noname> <noname> -- )
c-function __gmpz_set_q __gmpz_set_q a a -- void	( <noname> <noname> -- )
c-function __gmpz_set_si __gmpz_set_si a n -- void	( <noname> <noname> -- )
c-function __gmpz_set_str __gmpz_set_str a s n -- n	( <noname> <noname> <noname> -- )
c-function __gmpz_set_ui __gmpz_set_ui a u -- void	( <noname> <noname> -- )
c-function __gmpz_setbit __gmpz_setbit a u -- void	( <noname> <noname> -- )
c-function __gmpz_size __gmpz_size a -- n	( <noname> -- )
c-function __gmpz_sizeinbase __gmpz_sizeinbase a n -- n	( <noname> <noname> -- )
c-function __gmpz_sqrt __gmpz_sqrt a a -- void	( <noname> <noname> -- )
c-function __gmpz_sqrtrem __gmpz_sqrtrem a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_sub __gmpz_sub a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_sub_ui __gmpz_sub_ui a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_ui_sub __gmpz_ui_sub a u a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_submul __gmpz_submul a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_submul_ui __gmpz_submul_ui a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_swap __gmpz_swap a a -- void	( <noname> <noname> -- )
c-function __gmpz_tdiv_ui __gmpz_tdiv_ui a u -- u	( <noname> <noname> -- )
c-function __gmpz_tdiv_q __gmpz_tdiv_q a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_tdiv_q_2exp __gmpz_tdiv_q_2exp a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_tdiv_q_ui __gmpz_tdiv_q_ui a a u -- u	( <noname> <noname> <noname> -- )
c-function __gmpz_tdiv_qr __gmpz_tdiv_qr a a a a -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpz_tdiv_qr_ui __gmpz_tdiv_qr_ui a a a u -- u	( <noname> <noname> <noname> <noname> -- )
c-function __gmpz_tdiv_r __gmpz_tdiv_r a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_tdiv_r_2exp __gmpz_tdiv_r_2exp a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_tdiv_r_ui __gmpz_tdiv_r_ui a a u -- u	( <noname> <noname> <noname> -- )
c-function __gmpz_tstbit __gmpz_tstbit a u -- n	( <noname> <noname> -- )
c-function __gmpz_ui_pow_ui __gmpz_ui_pow_ui a u u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_urandomb __gmpz_urandomb a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_urandomm __gmpz_urandomm a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_xor __gmpz_xor a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpz_limbs_read __gmpz_limbs_read a -- a	( <noname> -- )
c-function __gmpz_limbs_write __gmpz_limbs_write a n -- a	( <noname> <noname> -- )
c-function __gmpz_limbs_modify __gmpz_limbs_modify a n -- a	( <noname> <noname> -- )
c-function __gmpz_limbs_finish __gmpz_limbs_finish a n -- void	( <noname> <noname> -- )
c-function __gmpz_roinit_n __gmpz_roinit_n a a n -- a	( <noname> <noname> <noname> -- )
c-function __gmpq_abs __gmpq_abs a a -- void	( <noname> <noname> -- )
c-function __gmpq_add __gmpq_add a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpq_canonicalize __gmpq_canonicalize a -- void	( <noname> -- )
c-function __gmpq_clear __gmpq_clear a -- void	( <noname> -- )
c-function __gmpq_clears __gmpq_clears a ... -- void	( <noname> <noname> -- )
c-function __gmpq_cmp __gmpq_cmp a a -- n	( <noname> <noname> -- )
c-function __gmpq_cmp_si __gmpq_cmp_si a n u -- n	( <noname> <noname> <noname> -- )
c-function __gmpq_cmp_ui __gmpq_cmp_ui a u u -- n	( <noname> <noname> <noname> -- )
c-function __gmpq_cmp_z __gmpq_cmp_z a a -- n	( <noname> <noname> -- )
c-function __gmpq_div __gmpq_div a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpq_div_2exp __gmpq_div_2exp a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpq_equal __gmpq_equal a a -- n	( <noname> <noname> -- )
c-function __gmpq_get_num __gmpq_get_num a a -- void	( <noname> <noname> -- )
c-function __gmpq_get_den __gmpq_get_den a a -- void	( <noname> <noname> -- )
c-function __gmpq_get_d __gmpq_get_d a -- r	( <noname> -- )
c-function __gmpq_get_str __gmpq_get_str a n a -- a	( <noname> <noname> <noname> -- )
c-function __gmpq_init __gmpq_init a -- void	( <noname> -- )
c-function __gmpq_inits __gmpq_inits a ... -- void	( <noname> <noname> -- )
c-function __gmpq_inp_str __gmpq_inp_str a a n -- n	( <noname> <noname> <noname> -- )
c-function __gmpq_inv __gmpq_inv a a -- void	( <noname> <noname> -- )
c-function __gmpq_mul __gmpq_mul a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpq_mul_2exp __gmpq_mul_2exp a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpq_neg __gmpq_neg a a -- void	( <noname> <noname> -- )
c-function __gmpq_out_str __gmpq_out_str a n a -- n	( <noname> <noname> <noname> -- )
c-function __gmpq_set __gmpq_set a a -- void	( <noname> <noname> -- )
c-function __gmpq_set_d __gmpq_set_d a r -- void	( <noname> <noname> -- )
c-function __gmpq_set_den __gmpq_set_den a a -- void	( <noname> <noname> -- )
c-function __gmpq_set_f __gmpq_set_f a a -- void	( <noname> <noname> -- )
c-function __gmpq_set_num __gmpq_set_num a a -- void	( <noname> <noname> -- )
c-function __gmpq_set_si __gmpq_set_si a n u -- void	( <noname> <noname> <noname> -- )
c-function __gmpq_set_str __gmpq_set_str a s n -- n	( <noname> <noname> <noname> -- )
c-function __gmpq_set_ui __gmpq_set_ui a u u -- void	( <noname> <noname> <noname> -- )
c-function __gmpq_set_z __gmpq_set_z a a -- void	( <noname> <noname> -- )
c-function __gmpq_sub __gmpq_sub a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpq_swap __gmpq_swap a a -- void	( <noname> <noname> -- )
c-function __gmpf_abs __gmpf_abs a a -- void	( <noname> <noname> -- )
c-function __gmpf_add __gmpf_add a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpf_add_ui __gmpf_add_ui a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpf_ceil __gmpf_ceil a a -- void	( <noname> <noname> -- )
c-function __gmpf_clear __gmpf_clear a -- void	( <noname> -- )
c-function __gmpf_clears __gmpf_clears a ... -- void	( <noname> <noname> -- )
c-function __gmpf_cmp __gmpf_cmp a a -- n	( <noname> <noname> -- )
c-function __gmpf_cmp_z __gmpf_cmp_z a a -- n	( <noname> <noname> -- )
c-function __gmpf_cmp_d __gmpf_cmp_d a r -- n	( <noname> <noname> -- )
c-function __gmpf_cmp_si __gmpf_cmp_si a n -- n	( <noname> <noname> -- )
c-function __gmpf_cmp_ui __gmpf_cmp_ui a u -- n	( <noname> <noname> -- )
c-function __gmpf_div __gmpf_div a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpf_div_2exp __gmpf_div_2exp a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpf_div_ui __gmpf_div_ui a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpf_dump __gmpf_dump a -- void	( <noname> -- )
c-function __gmpf_eq __gmpf_eq a a u -- n	( <noname> <noname> <noname> -- )
c-function __gmpf_fits_sint_p __gmpf_fits_sint_p a -- n	( <noname> -- )
c-function __gmpf_fits_slong_p __gmpf_fits_slong_p a -- n	( <noname> -- )
c-function __gmpf_fits_sshort_p __gmpf_fits_sshort_p a -- n	( <noname> -- )
c-function __gmpf_fits_uint_p __gmpf_fits_uint_p a -- n	( <noname> -- )
c-function __gmpf_fits_ulong_p __gmpf_fits_ulong_p a -- n	( <noname> -- )
c-function __gmpf_fits_ushort_p __gmpf_fits_ushort_p a -- n	( <noname> -- )
c-function __gmpf_floor __gmpf_floor a a -- void	( <noname> <noname> -- )
c-function __gmpf_get_d __gmpf_get_d a -- r	( <noname> -- )
c-function __gmpf_get_d_2exp __gmpf_get_d_2exp a a -- r	( <noname> <noname> -- )
c-function __gmpf_get_default_prec __gmpf_get_default_prec  -- u	( -- )
c-function __gmpf_get_prec __gmpf_get_prec a -- u	( <noname> -- )
c-function __gmpf_get_si __gmpf_get_si a -- n	( <noname> -- )
c-function __gmpf_get_str __gmpf_get_str a a n n a -- a	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpf_get_ui __gmpf_get_ui a -- u	( <noname> -- )
c-function __gmpf_init __gmpf_init a -- void	( <noname> -- )
c-function __gmpf_init2 __gmpf_init2 a u -- void	( <noname> <noname> -- )
c-function __gmpf_inits __gmpf_inits a ... -- void	( <noname> <noname> -- )
c-function __gmpf_init_set __gmpf_init_set a a -- void	( <noname> <noname> -- )
c-function __gmpf_init_set_d __gmpf_init_set_d a r -- void	( <noname> <noname> -- )
c-function __gmpf_init_set_si __gmpf_init_set_si a n -- void	( <noname> <noname> -- )
c-function __gmpf_init_set_str __gmpf_init_set_str a s n -- n	( <noname> <noname> <noname> -- )
c-function __gmpf_init_set_ui __gmpf_init_set_ui a u -- void	( <noname> <noname> -- )
c-function __gmpf_inp_str __gmpf_inp_str a a n -- n	( <noname> <noname> <noname> -- )
c-function __gmpf_integer_p __gmpf_integer_p a -- n	( <noname> -- )
c-function __gmpf_mul __gmpf_mul a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpf_mul_2exp __gmpf_mul_2exp a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpf_mul_ui __gmpf_mul_ui a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpf_neg __gmpf_neg a a -- void	( <noname> <noname> -- )
c-function __gmpf_out_str __gmpf_out_str a n n a -- n	( <noname> <noname> <noname> <noname> -- )
c-function __gmpf_pow_ui __gmpf_pow_ui a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpf_random2 __gmpf_random2 a n n -- void	( <noname> <noname> <noname> -- )
c-function __gmpf_reldiff __gmpf_reldiff a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpf_set __gmpf_set a a -- void	( <noname> <noname> -- )
c-function __gmpf_set_d __gmpf_set_d a r -- void	( <noname> <noname> -- )
c-function __gmpf_set_default_prec __gmpf_set_default_prec u -- void	( <noname> -- )
c-function __gmpf_set_prec __gmpf_set_prec a u -- void	( <noname> <noname> -- )
c-function __gmpf_set_prec_raw __gmpf_set_prec_raw a u -- void	( <noname> <noname> -- )
c-function __gmpf_set_q __gmpf_set_q a a -- void	( <noname> <noname> -- )
c-function __gmpf_set_si __gmpf_set_si a n -- void	( <noname> <noname> -- )
c-function __gmpf_set_str __gmpf_set_str a s n -- n	( <noname> <noname> <noname> -- )
c-function __gmpf_set_ui __gmpf_set_ui a u -- void	( <noname> <noname> -- )
c-function __gmpf_set_z __gmpf_set_z a a -- void	( <noname> <noname> -- )
c-function __gmpf_size __gmpf_size a -- n	( <noname> -- )
c-function __gmpf_sqrt __gmpf_sqrt a a -- void	( <noname> <noname> -- )
c-function __gmpf_sqrt_ui __gmpf_sqrt_ui a u -- void	( <noname> <noname> -- )
c-function __gmpf_sub __gmpf_sub a a a -- void	( <noname> <noname> <noname> -- )
c-function __gmpf_sub_ui __gmpf_sub_ui a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpf_swap __gmpf_swap a a -- void	( <noname> <noname> -- )
c-function __gmpf_trunc __gmpf_trunc a a -- void	( <noname> <noname> -- )
c-function __gmpf_ui_div __gmpf_ui_div a u a -- void	( <noname> <noname> <noname> -- )
c-function __gmpf_ui_sub __gmpf_ui_sub a u a -- void	( <noname> <noname> <noname> -- )
c-function __gmpf_urandomb __gmpf_urandomb a a u -- void	( <noname> <noname> <noname> -- )
c-function __gmpn_add __gmpn_add a a n a n -- u	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_add_1 __gmpn_add_1 a a n u -- u	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_add_n __gmpn_add_n a a a n -- u	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_addmul_1 __gmpn_addmul_1 a a n u -- u	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_cmp __gmpn_cmp a a n -- n	( <noname> <noname> <noname> -- )
c-function __gmpn_zero_p __gmpn_zero_p a n -- n	( <noname> <noname> -- )
c-function __gmpn_divexact_1 __gmpn_divexact_1 a a n u -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_divexact_by3c __gmpn_divexact_by3c a a n u -- u	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_divrem __gmpn_divrem a n a n a n -- u	( <noname> <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_divrem_1 __gmpn_divrem_1 a n a n u -- u	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_divrem_2 __gmpn_divrem_2 a n a n a -- u	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_div_qr_1 __gmpn_div_qr_1 a a a n u -- u	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_div_qr_2 __gmpn_div_qr_2 a a a n a -- u	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_gcd __gmpn_gcd a a n a n -- n	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_gcd_11 __gmpn_gcd_11 u u -- u	( <noname> <noname> -- )
c-function __gmpn_gcd_1 __gmpn_gcd_1 a n u -- u	( <noname> <noname> <noname> -- )
c-function __gmpn_gcdext_1 __gmpn_gcdext_1 a a u u -- u	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_gcdext __gmpn_gcdext a a a a n a n -- n	( <noname> <noname> <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_get_str __gmpn_get_str a n a n -- n	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_hamdist __gmpn_hamdist a a n -- u	( <noname> <noname> <noname> -- )
c-function __gmpn_lshift __gmpn_lshift a a n u -- u	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_mod_1 __gmpn_mod_1 a n u -- u	( <noname> <noname> <noname> -- )
c-function __gmpn_mul __gmpn_mul a a n a n -- u	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_mul_1 __gmpn_mul_1 a a n u -- u	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_mul_n __gmpn_mul_n a a a n -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_sqr __gmpn_sqr a a n -- void	( <noname> <noname> <noname> -- )
c-function __gmpn_neg __gmpn_neg a a n -- u	( <noname> <noname> <noname> -- )
c-function __gmpn_com __gmpn_com a a n -- void	( <noname> <noname> <noname> -- )
c-function __gmpn_perfect_square_p __gmpn_perfect_square_p a n -- n	( <noname> <noname> -- )
c-function __gmpn_perfect_power_p __gmpn_perfect_power_p a n -- n	( <noname> <noname> -- )
c-function __gmpn_popcount __gmpn_popcount a n -- u	( <noname> <noname> -- )
c-function __gmpn_pow_1 __gmpn_pow_1 a a n u a -- n	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_preinv_mod_1 __gmpn_preinv_mod_1 a n u u -- u	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_random __gmpn_random a n -- void	( <noname> <noname> -- )
c-function __gmpn_random2 __gmpn_random2 a n -- void	( <noname> <noname> -- )
c-function __gmpn_rshift __gmpn_rshift a a n u -- u	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_scan0 __gmpn_scan0 a u -- u	( <noname> <noname> -- )
c-function __gmpn_scan1 __gmpn_scan1 a u -- u	( <noname> <noname> -- )
c-function __gmpn_set_str __gmpn_set_str a a n n -- n	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_sizeinbase __gmpn_sizeinbase a n n -- n	( <noname> <noname> <noname> -- )
c-function __gmpn_sqrtrem __gmpn_sqrtrem a a a n -- n	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_sub __gmpn_sub a a n a n -- u	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_sub_1 __gmpn_sub_1 a a n u -- u	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_sub_n __gmpn_sub_n a a a n -- u	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_submul_1 __gmpn_submul_1 a a n u -- u	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_tdiv_qr __gmpn_tdiv_qr a a n a n a n -- void	( <noname> <noname> <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_and_n __gmpn_and_n a a a n -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_andn_n __gmpn_andn_n a a a n -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_nand_n __gmpn_nand_n a a a n -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_ior_n __gmpn_ior_n a a a n -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_iorn_n __gmpn_iorn_n a a a n -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_nior_n __gmpn_nior_n a a a n -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_xor_n __gmpn_xor_n a a a n -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_xnor_n __gmpn_xnor_n a a a n -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_copyi __gmpn_copyi a a n -- void	( <noname> <noname> <noname> -- )
c-function __gmpn_copyd __gmpn_copyd a a n -- void	( <noname> <noname> <noname> -- )
c-function __gmpn_zero __gmpn_zero a n -- void	( <noname> <noname> -- )
c-function __gmpn_cnd_add_n __gmpn_cnd_add_n u a a a n -- u	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_cnd_sub_n __gmpn_cnd_sub_n u a a a n -- u	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_sec_add_1 __gmpn_sec_add_1 a a n u a -- u	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_sec_add_1_itch __gmpn_sec_add_1_itch n -- n	( <noname> -- )
c-function __gmpn_sec_sub_1 __gmpn_sec_sub_1 a a n u a -- u	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_sec_sub_1_itch __gmpn_sec_sub_1_itch n -- n	( <noname> -- )
c-function __gmpn_cnd_swap __gmpn_cnd_swap u a a n -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_sec_mul __gmpn_sec_mul a a n a n a -- void	( <noname> <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_sec_mul_itch __gmpn_sec_mul_itch n n -- n	( <noname> <noname> -- )
c-function __gmpn_sec_sqr __gmpn_sec_sqr a a n a -- void	( <noname> <noname> <noname> <noname> -- )
c-function __gmpn_sec_sqr_itch __gmpn_sec_sqr_itch n -- n	( <noname> -- )
c-function __gmpn_sec_powm __gmpn_sec_powm a a n a u a n a -- void	( <noname> <noname> <noname> <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_sec_powm_itch __gmpn_sec_powm_itch n u n -- n	( <noname> <noname> <noname> -- )
c-function __gmpn_sec_tabselect __gmpn_sec_tabselect a a n n n -- void	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_sec_div_qr __gmpn_sec_div_qr a a n a n a -- u	( <noname> <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_sec_div_qr_itch __gmpn_sec_div_qr_itch n n -- n	( <noname> <noname> -- )
c-function __gmpn_sec_div_r __gmpn_sec_div_r a n a n a -- void	( <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_sec_div_r_itch __gmpn_sec_div_r_itch n n -- n	( <noname> <noname> -- )
c-function __gmpn_sec_invert __gmpn_sec_invert a a a n u a -- n	( <noname> <noname> <noname> <noname> <noname> <noname> -- )
c-function __gmpn_sec_invert_itch __gmpn_sec_invert_itch n -- n	( <noname> -- )

\ ----===< postfix >===-----
end-c-library
