\ This file has been generated using SWIG and fsi,
\ and is already platform dependent, search for the corresponding
\ fsi-file to compile it where no one has compiled it before ;)
\ Forth systems have their own own dynamic loader and don't need addional C-Code.
\ That's why this file will just print normal forth-code once compiled
\ and can be used directly with include or require.
\ As all comments are stripped during the compilation, please
\ insert the copyright notice of the original file here.

\ ----===< prefix >===-----
c-library avcodec
s" avcodec" add-lib
s" ((struct AV:x.spx[arg0]" ptr-declare $+[]!
\c #include <libavcodec/avcodec.h>
\c #include <libavutil/pixfmt.h>
\c #undef gforth_d2ll
\c #define gforth_d2ll(x1,x2) av_make_q(x1,x2)

\ ----===< int constants >===-----
#1	constant AV_CODEC_PROP_INTRA_ONLY
#2	constant AV_CODEC_PROP_LOSSY
#4	constant AV_CODEC_PROP_LOSSLESS
#8	constant AV_CODEC_PROP_REORDER
#65536	constant AV_CODEC_PROP_BITMAP_SUB
#131072	constant AV_CODEC_PROP_TEXT_SUB
#64	constant AV_INPUT_BUFFER_PADDING_SIZE
#16384	constant AV_INPUT_BUFFER_MIN_SIZE
#1	constant AV_CODEC_FLAG_UNALIGNED
#2	constant AV_CODEC_FLAG_QSCALE
#4	constant AV_CODEC_FLAG_4MV
#8	constant AV_CODEC_FLAG_OUTPUT_CORRUPT
#16	constant AV_CODEC_FLAG_QPEL
#32	constant AV_CODEC_FLAG_DROPCHANGED
#512	constant AV_CODEC_FLAG_PASS1
#1024	constant AV_CODEC_FLAG_PASS2
#2048	constant AV_CODEC_FLAG_LOOP_FILTER
#8192	constant AV_CODEC_FLAG_GRAY
#32768	constant AV_CODEC_FLAG_PSNR
#65536	constant AV_CODEC_FLAG_TRUNCATED
#262144	constant AV_CODEC_FLAG_INTERLACED_DCT
#524288	constant AV_CODEC_FLAG_LOW_DELAY
#4194304	constant AV_CODEC_FLAG_GLOBAL_HEADER
#8388608	constant AV_CODEC_FLAG_BITEXACT
#16777216	constant AV_CODEC_FLAG_AC_PRED
#536870912	constant AV_CODEC_FLAG_INTERLACED_ME
#2147483648	constant AV_CODEC_FLAG_CLOSED_GOP
#1	constant AV_CODEC_FLAG2_FAST
#4	constant AV_CODEC_FLAG2_NO_OUTPUT
#8	constant AV_CODEC_FLAG2_LOCAL_HEADER
#8192	constant AV_CODEC_FLAG2_DROP_FRAME_TIMECODE
#32768	constant AV_CODEC_FLAG2_CHUNKS
#65536	constant AV_CODEC_FLAG2_IGNORE_CROP
#4194304	constant AV_CODEC_FLAG2_SHOW_ALL
#268435456	constant AV_CODEC_FLAG2_EXPORT_MVS
#536870912	constant AV_CODEC_FLAG2_SKIP_MANUAL
#1073741824	constant AV_CODEC_FLAG2_RO_FLUSH_NOOP
#1	constant AV_CODEC_CAP_DRAW_HORIZ_BAND
#2	constant AV_CODEC_CAP_DR1
#8	constant AV_CODEC_CAP_TRUNCATED
#32	constant AV_CODEC_CAP_DELAY
#64	constant AV_CODEC_CAP_SMALL_LAST_FRAME
#256	constant AV_CODEC_CAP_SUBFRAMES
#512	constant AV_CODEC_CAP_EXPERIMENTAL
#1024	constant AV_CODEC_CAP_CHANNEL_CONF
#4096	constant AV_CODEC_CAP_FRAME_THREADS
#8192	constant AV_CODEC_CAP_SLICE_THREADS
#16384	constant AV_CODEC_CAP_PARAM_CHANGE
#32768	constant AV_CODEC_CAP_AUTO_THREADS
#65536	constant AV_CODEC_CAP_VARIABLE_FRAME_SIZE
#131072	constant AV_CODEC_CAP_AVOID_PROBING
#1073741824	constant AV_CODEC_CAP_INTRA_ONLY
#2147483648	constant AV_CODEC_CAP_LOSSLESS
#262144	constant AV_CODEC_CAP_HARDWARE
#524288	constant AV_CODEC_CAP_HYBRID
#1048576	constant AV_CODEC_CAP_ENCODER_REORDERED_OPAQUE
#1	constant AV_GET_BUFFER_FLAG_REF
#1	constant AV_PKT_FLAG_KEY
#2	constant AV_PKT_FLAG_CORRUPT
#4	constant AV_PKT_FLAG_DISCARD
#8	constant AV_PKT_FLAG_TRUSTED
#16	constant AV_PKT_FLAG_DISPOSABLE
#-1	constant FF_COMPRESSION_DEFAULT
#0	constant FF_CMP_SAD
#1	constant FF_CMP_SSE
#2	constant FF_CMP_SATD
#3	constant FF_CMP_DCT
#4	constant FF_CMP_PSNR
#5	constant FF_CMP_BIT
#6	constant FF_CMP_RD
#7	constant FF_CMP_ZERO
#8	constant FF_CMP_VSAD
#9	constant FF_CMP_VSSE
#10	constant FF_CMP_NSSE
#11	constant FF_CMP_W53
#12	constant FF_CMP_W97
#13	constant FF_CMP_DCTMAX
#14	constant FF_CMP_DCT264
#15	constant FF_CMP_MEDIAN_SAD
#256	constant FF_CMP_CHROMA
#1	constant SLICE_FLAG_CODED_ORDER
#2	constant SLICE_FLAG_ALLOW_FIELD
#4	constant SLICE_FLAG_ALLOW_PLANE
#0	constant FF_MB_DECISION_SIMPLE
#1	constant FF_MB_DECISION_BITS
#2	constant FF_MB_DECISION_RD
#1	constant FF_BUG_AUTODETECT
#4	constant FF_BUG_XVID_ILACE
#8	constant FF_BUG_UMP4
#16	constant FF_BUG_NO_PADDING
#32	constant FF_BUG_AMV
#64	constant FF_BUG_QPEL_CHROMA
#128	constant FF_BUG_STD_QPEL
#256	constant FF_BUG_QPEL_CHROMA2
#512	constant FF_BUG_DIRECT_BLOCKSIZE
#1024	constant FF_BUG_EDGE
#2048	constant FF_BUG_HPEL_CHROMA
#4096	constant FF_BUG_DC_CLIP
#8192	constant FF_BUG_MS
#16384	constant FF_BUG_TRUNCATED
#32768	constant FF_BUG_IEDGE
#2	constant FF_COMPLIANCE_VERY_STRICT
#1	constant FF_COMPLIANCE_STRICT
#0	constant FF_COMPLIANCE_NORMAL
#-1	constant FF_COMPLIANCE_UNOFFICIAL
#-2	constant FF_COMPLIANCE_EXPERIMENTAL
#1	constant FF_EC_GUESS_MVS
#2	constant FF_EC_DEBLOCK
#256	constant FF_EC_FAVOR_INTER
#1	constant FF_DEBUG_PICT_INFO
#2	constant FF_DEBUG_RC
#4	constant FF_DEBUG_BITSTREAM
#8	constant FF_DEBUG_MB_TYPE
#16	constant FF_DEBUG_QP
#64	constant FF_DEBUG_DCT_COEFF
#128	constant FF_DEBUG_SKIP
#256	constant FF_DEBUG_STARTCODE
#1024	constant FF_DEBUG_ER
#2048	constant FF_DEBUG_MMCO
#4096	constant FF_DEBUG_BUGS
#32768	constant FF_DEBUG_BUFFERS
#65536	constant FF_DEBUG_THREADS
#8388608	constant FF_DEBUG_GREEN_MD
#16777216	constant FF_DEBUG_NOMC
#1	constant AV_EF_CRCCHECK
#2	constant AV_EF_BITSTREAM
#4	constant AV_EF_BUFFER
#8	constant AV_EF_EXPLODE
#32768	constant AV_EF_IGNORE_ERR
#65536	constant AV_EF_CAREFUL
#131072	constant AV_EF_COMPLIANT
#262144	constant AV_EF_AGGRESSIVE
#0	constant FF_DCT_AUTO
#1	constant FF_DCT_FASTINT
#2	constant FF_DCT_INT
#3	constant FF_DCT_MMX
#5	constant FF_DCT_ALTIVEC
#6	constant FF_DCT_FAAN
#0	constant FF_IDCT_AUTO
#1	constant FF_IDCT_INT
#2	constant FF_IDCT_SIMPLE
#3	constant FF_IDCT_SIMPLEMMX
#7	constant FF_IDCT_ARM
#8	constant FF_IDCT_ALTIVEC
#10	constant FF_IDCT_SIMPLEARM
#14	constant FF_IDCT_XVID
#16	constant FF_IDCT_SIMPLEARMV5TE
#17	constant FF_IDCT_SIMPLEARMV6
#20	constant FF_IDCT_FAAN
#22	constant FF_IDCT_SIMPLENEON
#24	constant FF_IDCT_NONE
#128	constant FF_IDCT_SIMPLEAUTO
#1	constant FF_THREAD_FRAME
#2	constant FF_THREAD_SLICE
#-99	constant FF_PROFILE_UNKNOWN
#-100	constant FF_PROFILE_RESERVED
#0	constant FF_PROFILE_AAC_MAIN
#1	constant FF_PROFILE_AAC_LOW
#2	constant FF_PROFILE_AAC_SSR
#3	constant FF_PROFILE_AAC_LTP
#4	constant FF_PROFILE_AAC_HE
#28	constant FF_PROFILE_AAC_HE_V2
#22	constant FF_PROFILE_AAC_LD
#38	constant FF_PROFILE_AAC_ELD
#128	constant FF_PROFILE_MPEG2_AAC_LOW
#131	constant FF_PROFILE_MPEG2_AAC_HE
#0	constant FF_PROFILE_DNXHD
#1	constant FF_PROFILE_DNXHR_LB
#2	constant FF_PROFILE_DNXHR_SQ
#3	constant FF_PROFILE_DNXHR_HQ
#4	constant FF_PROFILE_DNXHR_HQX
#5	constant FF_PROFILE_DNXHR_444
#20	constant FF_PROFILE_DTS
#30	constant FF_PROFILE_DTS_ES
#40	constant FF_PROFILE_DTS_96_24
#50	constant FF_PROFILE_DTS_HD_HRA
#60	constant FF_PROFILE_DTS_HD_MA
#70	constant FF_PROFILE_DTS_EXPRESS
#0	constant FF_PROFILE_MPEG2_422
#1	constant FF_PROFILE_MPEG2_HIGH
#2	constant FF_PROFILE_MPEG2_SS
#3	constant FF_PROFILE_MPEG2_SNR_SCALABLE
#4	constant FF_PROFILE_MPEG2_MAIN
#5	constant FF_PROFILE_MPEG2_SIMPLE
#512	constant FF_PROFILE_H264_CONSTRAINED
#2048	constant FF_PROFILE_H264_INTRA
#66	constant FF_PROFILE_H264_BASELINE
#578	constant FF_PROFILE_H264_CONSTRAINED_BASELINE
#77	constant FF_PROFILE_H264_MAIN
#88	constant FF_PROFILE_H264_EXTENDED
#100	constant FF_PROFILE_H264_HIGH
#110	constant FF_PROFILE_H264_HIGH_10
#2158	constant FF_PROFILE_H264_HIGH_10_INTRA
#118	constant FF_PROFILE_H264_MULTIVIEW_HIGH
#122	constant FF_PROFILE_H264_HIGH_422
#2170	constant FF_PROFILE_H264_HIGH_422_INTRA
#128	constant FF_PROFILE_H264_STEREO_HIGH
#144	constant FF_PROFILE_H264_HIGH_444
#244	constant FF_PROFILE_H264_HIGH_444_PREDICTIVE
#2292	constant FF_PROFILE_H264_HIGH_444_INTRA
#44	constant FF_PROFILE_H264_CAVLC_444
#0	constant FF_PROFILE_VC1_SIMPLE
#1	constant FF_PROFILE_VC1_MAIN
#2	constant FF_PROFILE_VC1_COMPLEX
#3	constant FF_PROFILE_VC1_ADVANCED
#0	constant FF_PROFILE_MPEG4_SIMPLE
#1	constant FF_PROFILE_MPEG4_SIMPLE_SCALABLE
#2	constant FF_PROFILE_MPEG4_CORE
#3	constant FF_PROFILE_MPEG4_MAIN
#4	constant FF_PROFILE_MPEG4_N_BIT
#5	constant FF_PROFILE_MPEG4_SCALABLE_TEXTURE
#6	constant FF_PROFILE_MPEG4_SIMPLE_FACE_ANIMATION
#7	constant FF_PROFILE_MPEG4_BASIC_ANIMATED_TEXTURE
#8	constant FF_PROFILE_MPEG4_HYBRID
#9	constant FF_PROFILE_MPEG4_ADVANCED_REAL_TIME
#10	constant FF_PROFILE_MPEG4_CORE_SCALABLE
#11	constant FF_PROFILE_MPEG4_ADVANCED_CODING
#12	constant FF_PROFILE_MPEG4_ADVANCED_CORE
#13	constant FF_PROFILE_MPEG4_ADVANCED_SCALABLE_TEXTURE
#14	constant FF_PROFILE_MPEG4_SIMPLE_STUDIO
#15	constant FF_PROFILE_MPEG4_ADVANCED_SIMPLE
#1	constant FF_PROFILE_JPEG2000_CSTREAM_RESTRICTION_0
#2	constant FF_PROFILE_JPEG2000_CSTREAM_RESTRICTION_1
#32768	constant FF_PROFILE_JPEG2000_CSTREAM_NO_RESTRICTION
#3	constant FF_PROFILE_JPEG2000_DCINEMA_2K
#4	constant FF_PROFILE_JPEG2000_DCINEMA_4K
#0	constant FF_PROFILE_VP9_0
#1	constant FF_PROFILE_VP9_1
#2	constant FF_PROFILE_VP9_2
#3	constant FF_PROFILE_VP9_3
#1	constant FF_PROFILE_HEVC_MAIN
#2	constant FF_PROFILE_HEVC_MAIN_10
#3	constant FF_PROFILE_HEVC_MAIN_STILL_PICTURE
#4	constant FF_PROFILE_HEVC_REXT
#0	constant FF_PROFILE_AV1_MAIN
#1	constant FF_PROFILE_AV1_HIGH
#2	constant FF_PROFILE_AV1_PROFESSIONAL
#192	constant FF_PROFILE_MJPEG_HUFFMAN_BASELINE_DCT
#193	constant FF_PROFILE_MJPEG_HUFFMAN_EXTENDED_SEQUENTIAL_DCT
#194	constant FF_PROFILE_MJPEG_HUFFMAN_PROGRESSIVE_DCT
#195	constant FF_PROFILE_MJPEG_HUFFMAN_LOSSLESS
#247	constant FF_PROFILE_MJPEG_JPEG_LS
#1	constant FF_PROFILE_SBC_MSBC
#0	constant FF_PROFILE_PRORES_PROXY
#1	constant FF_PROFILE_PRORES_LT
#2	constant FF_PROFILE_PRORES_STANDARD
#3	constant FF_PROFILE_PRORES_HQ
#4	constant FF_PROFILE_PRORES_4444
#5	constant FF_PROFILE_PRORES_XQ
#0	constant FF_PROFILE_ARIB_PROFILE_A
#1	constant FF_PROFILE_ARIB_PROFILE_C
#-99	constant FF_LEVEL_UNKNOWN
#-1	constant FF_SUB_CHARENC_MODE_DO_NOTHING
#0	constant FF_SUB_CHARENC_MODE_AUTOMATIC
#1	constant FF_SUB_CHARENC_MODE_PRE_DECODER
#2	constant FF_SUB_CHARENC_MODE_IGNORE
#1	constant FF_DEBUG_VIS_MV_P_FOR
#2	constant FF_DEBUG_VIS_MV_B_FOR
#4	constant FF_DEBUG_VIS_MV_B_BACK
#1	constant FF_CODEC_PROPERTY_LOSSLESS
#2	constant FF_CODEC_PROPERTY_CLOSED_CAPTIONS
#0	constant FF_SUB_TEXT_FMT_ASS
#512	constant AV_HWACCEL_CODEC_CAP_EXPERIMENTAL
#1	constant AV_HWACCEL_FLAG_IGNORE_LEVEL
#2	constant AV_HWACCEL_FLAG_ALLOW_HIGH_DEPTH
#4	constant AV_HWACCEL_FLAG_ALLOW_PROFILE_MISMATCH
#1	constant AV_SUBTITLE_FLAG_FORCED
#4	constant AV_PARSER_PTS_NB
#1	constant PARSER_FLAG_COMPLETE_FRAMES
#2	constant PARSER_FLAG_ONCE
#4	constant PARSER_FLAG_FETCHED_OFFSET
#4096	constant PARSER_FLAG_USE_CODEC_TS
#1024	constant AVPALETTE_SIZE
#256	constant AVPALETTE_COUNT

\ --------===< enums >===---------
#0	constant AV_CODEC_ID_NONE
#1	constant AV_CODEC_ID_MPEG1VIDEO
#2	constant AV_CODEC_ID_MPEG2VIDEO
#3	constant AV_CODEC_ID_H261
#4	constant AV_CODEC_ID_H263
#5	constant AV_CODEC_ID_RV10
#6	constant AV_CODEC_ID_RV20
#7	constant AV_CODEC_ID_MJPEG
#8	constant AV_CODEC_ID_MJPEGB
#9	constant AV_CODEC_ID_LJPEG
#10	constant AV_CODEC_ID_SP5X
#11	constant AV_CODEC_ID_JPEGLS
#12	constant AV_CODEC_ID_MPEG4
#13	constant AV_CODEC_ID_RAWVIDEO
#14	constant AV_CODEC_ID_MSMPEG4V1
#15	constant AV_CODEC_ID_MSMPEG4V2
#16	constant AV_CODEC_ID_MSMPEG4V3
#17	constant AV_CODEC_ID_WMV1
#18	constant AV_CODEC_ID_WMV2
#19	constant AV_CODEC_ID_H263P
#20	constant AV_CODEC_ID_H263I
#21	constant AV_CODEC_ID_FLV1
#22	constant AV_CODEC_ID_SVQ1
#23	constant AV_CODEC_ID_SVQ3
#24	constant AV_CODEC_ID_DVVIDEO
#25	constant AV_CODEC_ID_HUFFYUV
#26	constant AV_CODEC_ID_CYUV
#27	constant AV_CODEC_ID_H264
#28	constant AV_CODEC_ID_INDEO3
#29	constant AV_CODEC_ID_VP3
#30	constant AV_CODEC_ID_THEORA
#31	constant AV_CODEC_ID_ASV1
#32	constant AV_CODEC_ID_ASV2
#33	constant AV_CODEC_ID_FFV1
#34	constant AV_CODEC_ID_4XM
#35	constant AV_CODEC_ID_VCR1
#36	constant AV_CODEC_ID_CLJR
#37	constant AV_CODEC_ID_MDEC
#38	constant AV_CODEC_ID_ROQ
#39	constant AV_CODEC_ID_INTERPLAY_VIDEO
#40	constant AV_CODEC_ID_XAN_WC3
#41	constant AV_CODEC_ID_XAN_WC4
#42	constant AV_CODEC_ID_RPZA
#43	constant AV_CODEC_ID_CINEPAK
#44	constant AV_CODEC_ID_WS_VQA
#45	constant AV_CODEC_ID_MSRLE
#46	constant AV_CODEC_ID_MSVIDEO1
#47	constant AV_CODEC_ID_IDCIN
#48	constant AV_CODEC_ID_8BPS
#49	constant AV_CODEC_ID_SMC
#50	constant AV_CODEC_ID_FLIC
#51	constant AV_CODEC_ID_TRUEMOTION1
#52	constant AV_CODEC_ID_VMDVIDEO
#53	constant AV_CODEC_ID_MSZH
#54	constant AV_CODEC_ID_ZLIB
#55	constant AV_CODEC_ID_QTRLE
#56	constant AV_CODEC_ID_TSCC
#57	constant AV_CODEC_ID_ULTI
#58	constant AV_CODEC_ID_QDRAW
#59	constant AV_CODEC_ID_VIXL
#60	constant AV_CODEC_ID_QPEG
#61	constant AV_CODEC_ID_PNG
#62	constant AV_CODEC_ID_PPM
#63	constant AV_CODEC_ID_PBM
#64	constant AV_CODEC_ID_PGM
#65	constant AV_CODEC_ID_PGMYUV
#66	constant AV_CODEC_ID_PAM
#67	constant AV_CODEC_ID_FFVHUFF
#68	constant AV_CODEC_ID_RV30
#69	constant AV_CODEC_ID_RV40
#70	constant AV_CODEC_ID_VC1
#71	constant AV_CODEC_ID_WMV3
#72	constant AV_CODEC_ID_LOCO
#73	constant AV_CODEC_ID_WNV1
#74	constant AV_CODEC_ID_AASC
#75	constant AV_CODEC_ID_INDEO2
#76	constant AV_CODEC_ID_FRAPS
#77	constant AV_CODEC_ID_TRUEMOTION2
#78	constant AV_CODEC_ID_BMP
#79	constant AV_CODEC_ID_CSCD
#80	constant AV_CODEC_ID_MMVIDEO
#81	constant AV_CODEC_ID_ZMBV
#82	constant AV_CODEC_ID_AVS
#83	constant AV_CODEC_ID_SMACKVIDEO
#84	constant AV_CODEC_ID_NUV
#85	constant AV_CODEC_ID_KMVC
#86	constant AV_CODEC_ID_FLASHSV
#87	constant AV_CODEC_ID_CAVS
#88	constant AV_CODEC_ID_JPEG2000
#89	constant AV_CODEC_ID_VMNC
#90	constant AV_CODEC_ID_VP5
#91	constant AV_CODEC_ID_VP6
#92	constant AV_CODEC_ID_VP6F
#93	constant AV_CODEC_ID_TARGA
#94	constant AV_CODEC_ID_DSICINVIDEO
#95	constant AV_CODEC_ID_TIERTEXSEQVIDEO
#96	constant AV_CODEC_ID_TIFF
#97	constant AV_CODEC_ID_GIF
#98	constant AV_CODEC_ID_DXA
#99	constant AV_CODEC_ID_DNXHD
#100	constant AV_CODEC_ID_THP
#101	constant AV_CODEC_ID_SGI
#102	constant AV_CODEC_ID_C93
#103	constant AV_CODEC_ID_BETHSOFTVID
#104	constant AV_CODEC_ID_PTX
#105	constant AV_CODEC_ID_TXD
#106	constant AV_CODEC_ID_VP6A
#107	constant AV_CODEC_ID_AMV
#108	constant AV_CODEC_ID_VB
#109	constant AV_CODEC_ID_PCX
#110	constant AV_CODEC_ID_SUNRAST
#111	constant AV_CODEC_ID_INDEO4
#112	constant AV_CODEC_ID_INDEO5
#113	constant AV_CODEC_ID_MIMIC
#114	constant AV_CODEC_ID_RL2
#115	constant AV_CODEC_ID_ESCAPE124
#116	constant AV_CODEC_ID_DIRAC
#117	constant AV_CODEC_ID_BFI
#118	constant AV_CODEC_ID_CMV
#119	constant AV_CODEC_ID_MOTIONPIXELS
#120	constant AV_CODEC_ID_TGV
#121	constant AV_CODEC_ID_TGQ
#122	constant AV_CODEC_ID_TQI
#123	constant AV_CODEC_ID_AURA
#124	constant AV_CODEC_ID_AURA2
#125	constant AV_CODEC_ID_V210X
#126	constant AV_CODEC_ID_TMV
#127	constant AV_CODEC_ID_V210
#128	constant AV_CODEC_ID_DPX
#129	constant AV_CODEC_ID_MAD
#130	constant AV_CODEC_ID_FRWU
#131	constant AV_CODEC_ID_FLASHSV2
#132	constant AV_CODEC_ID_CDGRAPHICS
#133	constant AV_CODEC_ID_R210
#134	constant AV_CODEC_ID_ANM
#135	constant AV_CODEC_ID_BINKVIDEO
#136	constant AV_CODEC_ID_IFF_ILBM
#137	constant AV_CODEC_ID_KGV1
#138	constant AV_CODEC_ID_YOP
#139	constant AV_CODEC_ID_VP8
#140	constant AV_CODEC_ID_PICTOR
#141	constant AV_CODEC_ID_ANSI
#142	constant AV_CODEC_ID_A64_MULTI
#143	constant AV_CODEC_ID_A64_MULTI5
#144	constant AV_CODEC_ID_R10K
#145	constant AV_CODEC_ID_MXPEG
#146	constant AV_CODEC_ID_LAGARITH
#147	constant AV_CODEC_ID_PRORES
#148	constant AV_CODEC_ID_JV
#149	constant AV_CODEC_ID_DFA
#150	constant AV_CODEC_ID_WMV3IMAGE
#151	constant AV_CODEC_ID_VC1IMAGE
#152	constant AV_CODEC_ID_UTVIDEO
#153	constant AV_CODEC_ID_BMV_VIDEO
#154	constant AV_CODEC_ID_VBLE
#155	constant AV_CODEC_ID_DXTORY
#156	constant AV_CODEC_ID_V410
#157	constant AV_CODEC_ID_XWD
#158	constant AV_CODEC_ID_CDXL
#159	constant AV_CODEC_ID_XBM
#160	constant AV_CODEC_ID_ZEROCODEC
#161	constant AV_CODEC_ID_MSS1
#162	constant AV_CODEC_ID_MSA1
#163	constant AV_CODEC_ID_TSCC2
#164	constant AV_CODEC_ID_MTS2
#165	constant AV_CODEC_ID_CLLC
#166	constant AV_CODEC_ID_MSS2
#167	constant AV_CODEC_ID_VP9
#168	constant AV_CODEC_ID_AIC
#169	constant AV_CODEC_ID_ESCAPE130
#170	constant AV_CODEC_ID_G2M
#171	constant AV_CODEC_ID_WEBP
#172	constant AV_CODEC_ID_HNM4_VIDEO
#173	constant AV_CODEC_ID_HEVC
#174	constant AV_CODEC_ID_FIC
#175	constant AV_CODEC_ID_ALIAS_PIX
#176	constant AV_CODEC_ID_BRENDER_PIX
#177	constant AV_CODEC_ID_PAF_VIDEO
#178	constant AV_CODEC_ID_EXR
#179	constant AV_CODEC_ID_VP7
#180	constant AV_CODEC_ID_SANM
#181	constant AV_CODEC_ID_SGIRLE
#182	constant AV_CODEC_ID_MVC1
#183	constant AV_CODEC_ID_MVC2
#184	constant AV_CODEC_ID_HQX
#185	constant AV_CODEC_ID_TDSC
#186	constant AV_CODEC_ID_HQ_HQA
#187	constant AV_CODEC_ID_HAP
#188	constant AV_CODEC_ID_DDS
#189	constant AV_CODEC_ID_DXV
#190	constant AV_CODEC_ID_SCREENPRESSO
#191	constant AV_CODEC_ID_RSCC
#192	constant AV_CODEC_ID_AVS2
#32768	constant AV_CODEC_ID_Y41P
#32769	constant AV_CODEC_ID_AVRP
#32770	constant AV_CODEC_ID_012V
#32771	constant AV_CODEC_ID_AVUI
#32772	constant AV_CODEC_ID_AYUV
#32773	constant AV_CODEC_ID_TARGA_Y216
#32774	constant AV_CODEC_ID_V308
#32775	constant AV_CODEC_ID_V408
#32776	constant AV_CODEC_ID_YUV4
#32777	constant AV_CODEC_ID_AVRN
#32778	constant AV_CODEC_ID_CPIA
#32779	constant AV_CODEC_ID_XFACE
#32780	constant AV_CODEC_ID_SNOW
#32781	constant AV_CODEC_ID_SMVJPEG
#32782	constant AV_CODEC_ID_APNG
#32783	constant AV_CODEC_ID_DAALA
#32784	constant AV_CODEC_ID_CFHD
#32785	constant AV_CODEC_ID_TRUEMOTION2RT
#32786	constant AV_CODEC_ID_M101
#32787	constant AV_CODEC_ID_MAGICYUV
#32788	constant AV_CODEC_ID_SHEERVIDEO
#32789	constant AV_CODEC_ID_YLC
#32790	constant AV_CODEC_ID_PSD
#32791	constant AV_CODEC_ID_PIXLET
#32792	constant AV_CODEC_ID_SPEEDHQ
#32793	constant AV_CODEC_ID_FMVC
#32794	constant AV_CODEC_ID_SCPR
#32795	constant AV_CODEC_ID_CLEARVIDEO
#32796	constant AV_CODEC_ID_XPM
#32797	constant AV_CODEC_ID_AV1
#32798	constant AV_CODEC_ID_BITPACKED
#32799	constant AV_CODEC_ID_MSCC
#32800	constant AV_CODEC_ID_SRGC
#32801	constant AV_CODEC_ID_SVG
#32802	constant AV_CODEC_ID_GDV
#32803	constant AV_CODEC_ID_FITS
#32804	constant AV_CODEC_ID_IMM4
#32805	constant AV_CODEC_ID_PROSUMER
#32806	constant AV_CODEC_ID_MWSC
#32807	constant AV_CODEC_ID_WCMV
#32808	constant AV_CODEC_ID_RASC
#32809	constant AV_CODEC_ID_HYMT
#32810	constant AV_CODEC_ID_ARBC
#32811	constant AV_CODEC_ID_AGM
#32812	constant AV_CODEC_ID_LSCR
#32813	constant AV_CODEC_ID_VP4
#65536	constant AV_CODEC_ID_FIRST_AUDIO
#65536	constant AV_CODEC_ID_PCM_S16LE
#65537	constant AV_CODEC_ID_PCM_S16BE
#65538	constant AV_CODEC_ID_PCM_U16LE
#65539	constant AV_CODEC_ID_PCM_U16BE
#65540	constant AV_CODEC_ID_PCM_S8
#65541	constant AV_CODEC_ID_PCM_U8
#65542	constant AV_CODEC_ID_PCM_MULAW
#65543	constant AV_CODEC_ID_PCM_ALAW
#65544	constant AV_CODEC_ID_PCM_S32LE
#65545	constant AV_CODEC_ID_PCM_S32BE
#65546	constant AV_CODEC_ID_PCM_U32LE
#65547	constant AV_CODEC_ID_PCM_U32BE
#65548	constant AV_CODEC_ID_PCM_S24LE
#65549	constant AV_CODEC_ID_PCM_S24BE
#65550	constant AV_CODEC_ID_PCM_U24LE
#65551	constant AV_CODEC_ID_PCM_U24BE
#65552	constant AV_CODEC_ID_PCM_S24DAUD
#65553	constant AV_CODEC_ID_PCM_ZORK
#65554	constant AV_CODEC_ID_PCM_S16LE_PLANAR
#65555	constant AV_CODEC_ID_PCM_DVD
#65556	constant AV_CODEC_ID_PCM_F32BE
#65557	constant AV_CODEC_ID_PCM_F32LE
#65558	constant AV_CODEC_ID_PCM_F64BE
#65559	constant AV_CODEC_ID_PCM_F64LE
#65560	constant AV_CODEC_ID_PCM_BLURAY
#65561	constant AV_CODEC_ID_PCM_LXF
#65562	constant AV_CODEC_ID_S302M
#65563	constant AV_CODEC_ID_PCM_S8_PLANAR
#65564	constant AV_CODEC_ID_PCM_S24LE_PLANAR
#65565	constant AV_CODEC_ID_PCM_S32LE_PLANAR
#65566	constant AV_CODEC_ID_PCM_S16BE_PLANAR
#67584	constant AV_CODEC_ID_PCM_S64LE
#67585	constant AV_CODEC_ID_PCM_S64BE
#67586	constant AV_CODEC_ID_PCM_F16LE
#67587	constant AV_CODEC_ID_PCM_F24LE
#67588	constant AV_CODEC_ID_PCM_VIDC
#69632	constant AV_CODEC_ID_ADPCM_IMA_QT
#69633	constant AV_CODEC_ID_ADPCM_IMA_WAV
#69634	constant AV_CODEC_ID_ADPCM_IMA_DK3
#69635	constant AV_CODEC_ID_ADPCM_IMA_DK4
#69636	constant AV_CODEC_ID_ADPCM_IMA_WS
#69637	constant AV_CODEC_ID_ADPCM_IMA_SMJPEG
#69638	constant AV_CODEC_ID_ADPCM_MS
#69639	constant AV_CODEC_ID_ADPCM_4XM
#69640	constant AV_CODEC_ID_ADPCM_XA
#69641	constant AV_CODEC_ID_ADPCM_ADX
#69642	constant AV_CODEC_ID_ADPCM_EA
#69643	constant AV_CODEC_ID_ADPCM_G726
#69644	constant AV_CODEC_ID_ADPCM_CT
#69645	constant AV_CODEC_ID_ADPCM_SWF
#69646	constant AV_CODEC_ID_ADPCM_YAMAHA
#69647	constant AV_CODEC_ID_ADPCM_SBPRO_4
#69648	constant AV_CODEC_ID_ADPCM_SBPRO_3
#69649	constant AV_CODEC_ID_ADPCM_SBPRO_2
#69650	constant AV_CODEC_ID_ADPCM_THP
#69651	constant AV_CODEC_ID_ADPCM_IMA_AMV
#69652	constant AV_CODEC_ID_ADPCM_EA_R1
#69653	constant AV_CODEC_ID_ADPCM_EA_R3
#69654	constant AV_CODEC_ID_ADPCM_EA_R2
#69655	constant AV_CODEC_ID_ADPCM_IMA_EA_SEAD
#69656	constant AV_CODEC_ID_ADPCM_IMA_EA_EACS
#69657	constant AV_CODEC_ID_ADPCM_EA_XAS
#69658	constant AV_CODEC_ID_ADPCM_EA_MAXIS_XA
#69659	constant AV_CODEC_ID_ADPCM_IMA_ISS
#69660	constant AV_CODEC_ID_ADPCM_G722
#69661	constant AV_CODEC_ID_ADPCM_IMA_APC
#69662	constant AV_CODEC_ID_ADPCM_VIMA
#71680	constant AV_CODEC_ID_ADPCM_AFC
#71681	constant AV_CODEC_ID_ADPCM_IMA_OKI
#71682	constant AV_CODEC_ID_ADPCM_DTK
#71683	constant AV_CODEC_ID_ADPCM_IMA_RAD
#71684	constant AV_CODEC_ID_ADPCM_G726LE
#71685	constant AV_CODEC_ID_ADPCM_THP_LE
#71686	constant AV_CODEC_ID_ADPCM_PSX
#71687	constant AV_CODEC_ID_ADPCM_AICA
#71688	constant AV_CODEC_ID_ADPCM_IMA_DAT4
#71689	constant AV_CODEC_ID_ADPCM_MTAF
#71690	constant AV_CODEC_ID_ADPCM_AGM
#73728	constant AV_CODEC_ID_AMR_NB
#73729	constant AV_CODEC_ID_AMR_WB
#77824	constant AV_CODEC_ID_RA_144
#77825	constant AV_CODEC_ID_RA_288
#81920	constant AV_CODEC_ID_ROQ_DPCM
#81921	constant AV_CODEC_ID_INTERPLAY_DPCM
#81922	constant AV_CODEC_ID_XAN_DPCM
#81923	constant AV_CODEC_ID_SOL_DPCM
#83968	constant AV_CODEC_ID_SDX2_DPCM
#83969	constant AV_CODEC_ID_GREMLIN_DPCM
#86016	constant AV_CODEC_ID_MP2
#86017	constant AV_CODEC_ID_MP3
#86018	constant AV_CODEC_ID_AAC
#86019	constant AV_CODEC_ID_AC3
#86020	constant AV_CODEC_ID_DTS
#86021	constant AV_CODEC_ID_VORBIS
#86022	constant AV_CODEC_ID_DVAUDIO
#86023	constant AV_CODEC_ID_WMAV1
#86024	constant AV_CODEC_ID_WMAV2
#86025	constant AV_CODEC_ID_MACE3
#86026	constant AV_CODEC_ID_MACE6
#86027	constant AV_CODEC_ID_VMDAUDIO
#86028	constant AV_CODEC_ID_FLAC
#86029	constant AV_CODEC_ID_MP3ADU
#86030	constant AV_CODEC_ID_MP3ON4
#86031	constant AV_CODEC_ID_SHORTEN
#86032	constant AV_CODEC_ID_ALAC
#86033	constant AV_CODEC_ID_WESTWOOD_SND1
#86034	constant AV_CODEC_ID_GSM
#86035	constant AV_CODEC_ID_QDM2
#86036	constant AV_CODEC_ID_COOK
#86037	constant AV_CODEC_ID_TRUESPEECH
#86038	constant AV_CODEC_ID_TTA
#86039	constant AV_CODEC_ID_SMACKAUDIO
#86040	constant AV_CODEC_ID_QCELP
#86041	constant AV_CODEC_ID_WAVPACK
#86042	constant AV_CODEC_ID_DSICINAUDIO
#86043	constant AV_CODEC_ID_IMC
#86044	constant AV_CODEC_ID_MUSEPACK7
#86045	constant AV_CODEC_ID_MLP
#86046	constant AV_CODEC_ID_GSM_MS
#86047	constant AV_CODEC_ID_ATRAC3
#86048	constant AV_CODEC_ID_APE
#86049	constant AV_CODEC_ID_NELLYMOSER
#86050	constant AV_CODEC_ID_MUSEPACK8
#86051	constant AV_CODEC_ID_SPEEX
#86052	constant AV_CODEC_ID_WMAVOICE
#86053	constant AV_CODEC_ID_WMAPRO
#86054	constant AV_CODEC_ID_WMALOSSLESS
#86055	constant AV_CODEC_ID_ATRAC3P
#86056	constant AV_CODEC_ID_EAC3
#86057	constant AV_CODEC_ID_SIPR
#86058	constant AV_CODEC_ID_MP1
#86059	constant AV_CODEC_ID_TWINVQ
#86060	constant AV_CODEC_ID_TRUEHD
#86061	constant AV_CODEC_ID_MP4ALS
#86062	constant AV_CODEC_ID_ATRAC1
#86063	constant AV_CODEC_ID_BINKAUDIO_RDFT
#86064	constant AV_CODEC_ID_BINKAUDIO_DCT
#86065	constant AV_CODEC_ID_AAC_LATM
#86066	constant AV_CODEC_ID_QDMC
#86067	constant AV_CODEC_ID_CELT
#86068	constant AV_CODEC_ID_G723_1
#86069	constant AV_CODEC_ID_G729
#86070	constant AV_CODEC_ID_8SVX_EXP
#86071	constant AV_CODEC_ID_8SVX_FIB
#86072	constant AV_CODEC_ID_BMV_AUDIO
#86073	constant AV_CODEC_ID_RALF
#86074	constant AV_CODEC_ID_IAC
#86075	constant AV_CODEC_ID_ILBC
#86076	constant AV_CODEC_ID_OPUS
#86077	constant AV_CODEC_ID_COMFORT_NOISE
#86078	constant AV_CODEC_ID_TAK
#86079	constant AV_CODEC_ID_METASOUND
#86080	constant AV_CODEC_ID_PAF_AUDIO
#86081	constant AV_CODEC_ID_ON2AVC
#86082	constant AV_CODEC_ID_DSS_SP
#86083	constant AV_CODEC_ID_CODEC2
#88064	constant AV_CODEC_ID_FFWAVESYNTH
#88065	constant AV_CODEC_ID_SONIC
#88066	constant AV_CODEC_ID_SONIC_LS
#88067	constant AV_CODEC_ID_EVRC
#88068	constant AV_CODEC_ID_SMV
#88069	constant AV_CODEC_ID_DSD_LSBF
#88070	constant AV_CODEC_ID_DSD_MSBF
#88071	constant AV_CODEC_ID_DSD_LSBF_PLANAR
#88072	constant AV_CODEC_ID_DSD_MSBF_PLANAR
#88073	constant AV_CODEC_ID_4GV
#88074	constant AV_CODEC_ID_INTERPLAY_ACM
#88075	constant AV_CODEC_ID_XMA1
#88076	constant AV_CODEC_ID_XMA2
#88077	constant AV_CODEC_ID_DST
#88078	constant AV_CODEC_ID_ATRAC3AL
#88079	constant AV_CODEC_ID_ATRAC3PAL
#88080	constant AV_CODEC_ID_DOLBY_E
#88081	constant AV_CODEC_ID_APTX
#88082	constant AV_CODEC_ID_APTX_HD
#88083	constant AV_CODEC_ID_SBC
#88084	constant AV_CODEC_ID_ATRAC9
#88085	constant AV_CODEC_ID_HCOM
#94208	constant AV_CODEC_ID_FIRST_SUBTITLE
#94208	constant AV_CODEC_ID_DVD_SUBTITLE
#94209	constant AV_CODEC_ID_DVB_SUBTITLE
#94210	constant AV_CODEC_ID_TEXT
#94211	constant AV_CODEC_ID_XSUB
#94212	constant AV_CODEC_ID_SSA
#94213	constant AV_CODEC_ID_MOV_TEXT
#94214	constant AV_CODEC_ID_HDMV_PGS_SUBTITLE
#94215	constant AV_CODEC_ID_DVB_TELETEXT
#94216	constant AV_CODEC_ID_SRT
#96256	constant AV_CODEC_ID_MICRODVD
#96257	constant AV_CODEC_ID_EIA_608
#96258	constant AV_CODEC_ID_JACOSUB
#96259	constant AV_CODEC_ID_SAMI
#96260	constant AV_CODEC_ID_REALTEXT
#96261	constant AV_CODEC_ID_STL
#96262	constant AV_CODEC_ID_SUBVIEWER1
#96263	constant AV_CODEC_ID_SUBVIEWER
#96264	constant AV_CODEC_ID_SUBRIP
#96265	constant AV_CODEC_ID_WEBVTT
#96266	constant AV_CODEC_ID_MPL2
#96267	constant AV_CODEC_ID_VPLAYER
#96268	constant AV_CODEC_ID_PJS
#96269	constant AV_CODEC_ID_ASS
#96270	constant AV_CODEC_ID_HDMV_TEXT_SUBTITLE
#96271	constant AV_CODEC_ID_TTML
#96272	constant AV_CODEC_ID_ARIB_CAPTION
#98304	constant AV_CODEC_ID_FIRST_UNKNOWN
#98304	constant AV_CODEC_ID_TTF
#98305	constant AV_CODEC_ID_SCTE_35
#100352	constant AV_CODEC_ID_BINTEXT
#100353	constant AV_CODEC_ID_XBIN
#100354	constant AV_CODEC_ID_IDF
#100355	constant AV_CODEC_ID_OTF
#100356	constant AV_CODEC_ID_SMPTE_KLV
#100357	constant AV_CODEC_ID_DVD_NAV
#100358	constant AV_CODEC_ID_TIMED_ID3
#100359	constant AV_CODEC_ID_BIN_DATA
#102400	constant AV_CODEC_ID_PROBE
#131072	constant AV_CODEC_ID_MPEG2TS
#131073	constant AV_CODEC_ID_MPEG4SYSTEMS
#135168	constant AV_CODEC_ID_FFMETADATA
#135169	constant AV_CODEC_ID_WRAPPED_AVFRAME
#-16	constant AVDISCARD_NONE
#0	constant AVDISCARD_DEFAULT
#8	constant AVDISCARD_NONREF
#16	constant AVDISCARD_BIDIR
#24	constant AVDISCARD_NONINTRA
#32	constant AVDISCARD_NONKEY
#48	constant AVDISCARD_ALL
#0	constant AV_AUDIO_SERVICE_TYPE_MAIN
#1	constant AV_AUDIO_SERVICE_TYPE_EFFECTS
#2	constant AV_AUDIO_SERVICE_TYPE_VISUALLY_IMPAIRED
#3	constant AV_AUDIO_SERVICE_TYPE_HEARING_IMPAIRED
#4	constant AV_AUDIO_SERVICE_TYPE_DIALOGUE
#5	constant AV_AUDIO_SERVICE_TYPE_COMMENTARY
#6	constant AV_AUDIO_SERVICE_TYPE_EMERGENCY
#7	constant AV_AUDIO_SERVICE_TYPE_VOICE_OVER
#8	constant AV_AUDIO_SERVICE_TYPE_KARAOKE
#9	constant AV_AUDIO_SERVICE_TYPE_NB
#0	constant AV_PKT_DATA_PALETTE
#1	constant AV_PKT_DATA_NEW_EXTRADATA
#2	constant AV_PKT_DATA_PARAM_CHANGE
#3	constant AV_PKT_DATA_H263_MB_INFO
#4	constant AV_PKT_DATA_REPLAYGAIN
#5	constant AV_PKT_DATA_DISPLAYMATRIX
#6	constant AV_PKT_DATA_STEREO3D
#7	constant AV_PKT_DATA_AUDIO_SERVICE_TYPE
#8	constant AV_PKT_DATA_QUALITY_STATS
#9	constant AV_PKT_DATA_FALLBACK_TRACK
#10	constant AV_PKT_DATA_CPB_PROPERTIES
#11	constant AV_PKT_DATA_SKIP_SAMPLES
#12	constant AV_PKT_DATA_JP_DUALMONO
#13	constant AV_PKT_DATA_STRINGS_METADATA
#14	constant AV_PKT_DATA_SUBTITLE_POSITION
#15	constant AV_PKT_DATA_MATROSKA_BLOCKADDITIONAL
#16	constant AV_PKT_DATA_WEBVTT_IDENTIFIER
#17	constant AV_PKT_DATA_WEBVTT_SETTINGS
#18	constant AV_PKT_DATA_METADATA_UPDATE
#19	constant AV_PKT_DATA_MPEGTS_STREAM_ID
#20	constant AV_PKT_DATA_MASTERING_DISPLAY_METADATA
#21	constant AV_PKT_DATA_SPHERICAL
#22	constant AV_PKT_DATA_CONTENT_LIGHT_LEVEL
#23	constant AV_PKT_DATA_A53_CC
#24	constant AV_PKT_DATA_ENCRYPTION_INIT_INFO
#25	constant AV_PKT_DATA_ENCRYPTION_INFO
#26	constant AV_PKT_DATA_AFD
#27	constant AV_PKT_DATA_NB
#1	constant AV_SIDE_DATA_PARAM_CHANGE_CHANNEL_COUNT
#2	constant AV_SIDE_DATA_PARAM_CHANGE_CHANNEL_LAYOUT
#4	constant AV_SIDE_DATA_PARAM_CHANGE_SAMPLE_RATE
#8	constant AV_SIDE_DATA_PARAM_CHANGE_DIMENSIONS
#0	constant AV_FIELD_UNKNOWN
#1	constant AV_FIELD_PROGRESSIVE
#2	constant AV_FIELD_TT
#3	constant AV_FIELD_BB
#4	constant AV_FIELD_TB
#5	constant AV_FIELD_BT
#1	constant AV_CODEC_HW_CONFIG_METHOD_HW_DEVICE_CTX
#2	constant AV_CODEC_HW_CONFIG_METHOD_HW_FRAMES_CTX
#4	constant AV_CODEC_HW_CONFIG_METHOD_INTERNAL
#8	constant AV_CODEC_HW_CONFIG_METHOD_AD_HOC
#0	constant SUBTITLE_NONE
#1	constant SUBTITLE_BITMAP
#2	constant SUBTITLE_TEXT
#3	constant SUBTITLE_ASS
#0	constant AV_PICTURE_STRUCTURE_UNKNOWN
#1	constant AV_PICTURE_STRUCTURE_TOP_FIELD
#2	constant AV_PICTURE_STRUCTURE_BOTTOM_FIELD
#3	constant AV_PICTURE_STRUCTURE_FRAME
#-1	constant AV_PIX_FMT_NONE
#0	constant AV_PIX_FMT_YUV420P
#1	constant AV_PIX_FMT_YUYV422
#2	constant AV_PIX_FMT_RGB24
#3	constant AV_PIX_FMT_BGR24
#4	constant AV_PIX_FMT_YUV422P
#5	constant AV_PIX_FMT_YUV444P
#6	constant AV_PIX_FMT_YUV410P
#7	constant AV_PIX_FMT_YUV411P
#8	constant AV_PIX_FMT_GRAY8
#9	constant AV_PIX_FMT_MONOWHITE
#10	constant AV_PIX_FMT_MONOBLACK
#11	constant AV_PIX_FMT_PAL8
#12	constant AV_PIX_FMT_YUVJ420P
#13	constant AV_PIX_FMT_YUVJ422P
#14	constant AV_PIX_FMT_YUVJ444P
#15	constant AV_PIX_FMT_UYVY422
#16	constant AV_PIX_FMT_UYYVYY411
#17	constant AV_PIX_FMT_BGR8
#18	constant AV_PIX_FMT_BGR4
#19	constant AV_PIX_FMT_BGR4_BYTE
#20	constant AV_PIX_FMT_RGB8
#21	constant AV_PIX_FMT_RGB4
#22	constant AV_PIX_FMT_RGB4_BYTE
#23	constant AV_PIX_FMT_NV12
#24	constant AV_PIX_FMT_NV21
#25	constant AV_PIX_FMT_ARGB
#26	constant AV_PIX_FMT_RGBA
#27	constant AV_PIX_FMT_ABGR
#28	constant AV_PIX_FMT_BGRA
#29	constant AV_PIX_FMT_GRAY16BE
#30	constant AV_PIX_FMT_GRAY16LE
#31	constant AV_PIX_FMT_YUV440P
#32	constant AV_PIX_FMT_YUVJ440P
#33	constant AV_PIX_FMT_YUVA420P
#34	constant AV_PIX_FMT_RGB48BE
#35	constant AV_PIX_FMT_RGB48LE
#36	constant AV_PIX_FMT_RGB565BE
#37	constant AV_PIX_FMT_RGB565LE
#38	constant AV_PIX_FMT_RGB555BE
#39	constant AV_PIX_FMT_RGB555LE
#40	constant AV_PIX_FMT_BGR565BE
#41	constant AV_PIX_FMT_BGR565LE
#42	constant AV_PIX_FMT_BGR555BE
#43	constant AV_PIX_FMT_BGR555LE
#46	constant AV_PIX_FMT_VAAPI
#47	constant AV_PIX_FMT_YUV420P16LE
#48	constant AV_PIX_FMT_YUV420P16BE
#49	constant AV_PIX_FMT_YUV422P16LE
#50	constant AV_PIX_FMT_YUV422P16BE
#51	constant AV_PIX_FMT_YUV444P16LE
#52	constant AV_PIX_FMT_YUV444P16BE
#53	constant AV_PIX_FMT_DXVA2_VLD
#54	constant AV_PIX_FMT_RGB444LE
#55	constant AV_PIX_FMT_RGB444BE
#56	constant AV_PIX_FMT_BGR444LE
#57	constant AV_PIX_FMT_BGR444BE
#58	constant AV_PIX_FMT_YA8
#58	constant AV_PIX_FMT_Y400A
#58	constant AV_PIX_FMT_GRAY8A
#59	constant AV_PIX_FMT_BGR48BE
#60	constant AV_PIX_FMT_BGR48LE
#61	constant AV_PIX_FMT_YUV420P9BE
#62	constant AV_PIX_FMT_YUV420P9LE
#63	constant AV_PIX_FMT_YUV420P10BE
#64	constant AV_PIX_FMT_YUV420P10LE
#65	constant AV_PIX_FMT_YUV422P10BE
#66	constant AV_PIX_FMT_YUV422P10LE
#67	constant AV_PIX_FMT_YUV444P9BE
#68	constant AV_PIX_FMT_YUV444P9LE
#69	constant AV_PIX_FMT_YUV444P10BE
#70	constant AV_PIX_FMT_YUV444P10LE
#71	constant AV_PIX_FMT_YUV422P9BE
#72	constant AV_PIX_FMT_YUV422P9LE
#73	constant AV_PIX_FMT_GBRP
#73	constant AV_PIX_FMT_GBR24P
#74	constant AV_PIX_FMT_GBRP9BE
#75	constant AV_PIX_FMT_GBRP9LE
#76	constant AV_PIX_FMT_GBRP10BE
#77	constant AV_PIX_FMT_GBRP10LE
#78	constant AV_PIX_FMT_GBRP16BE
#79	constant AV_PIX_FMT_GBRP16LE
#80	constant AV_PIX_FMT_YUVA422P
#81	constant AV_PIX_FMT_YUVA444P
#82	constant AV_PIX_FMT_YUVA420P9BE
#83	constant AV_PIX_FMT_YUVA420P9LE
#84	constant AV_PIX_FMT_YUVA422P9BE
#85	constant AV_PIX_FMT_YUVA422P9LE
#86	constant AV_PIX_FMT_YUVA444P9BE
#87	constant AV_PIX_FMT_YUVA444P9LE
#88	constant AV_PIX_FMT_YUVA420P10BE
#89	constant AV_PIX_FMT_YUVA420P10LE
#90	constant AV_PIX_FMT_YUVA422P10BE
#91	constant AV_PIX_FMT_YUVA422P10LE
#92	constant AV_PIX_FMT_YUVA444P10BE
#93	constant AV_PIX_FMT_YUVA444P10LE
#94	constant AV_PIX_FMT_YUVA420P16BE
#95	constant AV_PIX_FMT_YUVA420P16LE
#96	constant AV_PIX_FMT_YUVA422P16BE
#97	constant AV_PIX_FMT_YUVA422P16LE
#98	constant AV_PIX_FMT_YUVA444P16BE
#99	constant AV_PIX_FMT_YUVA444P16LE
#100	constant AV_PIX_FMT_VDPAU
#101	constant AV_PIX_FMT_XYZ12LE
#102	constant AV_PIX_FMT_XYZ12BE
#103	constant AV_PIX_FMT_NV16
#104	constant AV_PIX_FMT_NV20LE
#105	constant AV_PIX_FMT_NV20BE
#106	constant AV_PIX_FMT_RGBA64BE
#107	constant AV_PIX_FMT_RGBA64LE
#108	constant AV_PIX_FMT_BGRA64BE
#109	constant AV_PIX_FMT_BGRA64LE
#110	constant AV_PIX_FMT_YVYU422
#111	constant AV_PIX_FMT_YA16BE
#112	constant AV_PIX_FMT_YA16LE
#113	constant AV_PIX_FMT_GBRAP
#114	constant AV_PIX_FMT_GBRAP16BE
#115	constant AV_PIX_FMT_GBRAP16LE
#116	constant AV_PIX_FMT_QSV
#117	constant AV_PIX_FMT_MMAL
#118	constant AV_PIX_FMT_D3D11VA_VLD
#119	constant AV_PIX_FMT_CUDA
#120	constant AV_PIX_FMT_0RGB
#121	constant AV_PIX_FMT_RGB0
#122	constant AV_PIX_FMT_0BGR
#123	constant AV_PIX_FMT_BGR0
#124	constant AV_PIX_FMT_YUV420P12BE
#125	constant AV_PIX_FMT_YUV420P12LE
#126	constant AV_PIX_FMT_YUV420P14BE
#127	constant AV_PIX_FMT_YUV420P14LE
#128	constant AV_PIX_FMT_YUV422P12BE
#129	constant AV_PIX_FMT_YUV422P12LE
#130	constant AV_PIX_FMT_YUV422P14BE
#131	constant AV_PIX_FMT_YUV422P14LE
#132	constant AV_PIX_FMT_YUV444P12BE
#133	constant AV_PIX_FMT_YUV444P12LE
#134	constant AV_PIX_FMT_YUV444P14BE
#135	constant AV_PIX_FMT_YUV444P14LE
#136	constant AV_PIX_FMT_GBRP12BE
#137	constant AV_PIX_FMT_GBRP12LE
#138	constant AV_PIX_FMT_GBRP14BE
#139	constant AV_PIX_FMT_GBRP14LE
#140	constant AV_PIX_FMT_YUVJ411P
#141	constant AV_PIX_FMT_BAYER_BGGR8
#142	constant AV_PIX_FMT_BAYER_RGGB8
#143	constant AV_PIX_FMT_BAYER_GBRG8
#144	constant AV_PIX_FMT_BAYER_GRBG8
#145	constant AV_PIX_FMT_BAYER_BGGR16LE
#146	constant AV_PIX_FMT_BAYER_BGGR16BE
#147	constant AV_PIX_FMT_BAYER_RGGB16LE
#148	constant AV_PIX_FMT_BAYER_RGGB16BE
#149	constant AV_PIX_FMT_BAYER_GBRG16LE
#150	constant AV_PIX_FMT_BAYER_GBRG16BE
#151	constant AV_PIX_FMT_BAYER_GRBG16LE
#152	constant AV_PIX_FMT_BAYER_GRBG16BE
#153	constant AV_PIX_FMT_XVMC
#154	constant AV_PIX_FMT_YUV440P10LE
#155	constant AV_PIX_FMT_YUV440P10BE
#156	constant AV_PIX_FMT_YUV440P12LE
#157	constant AV_PIX_FMT_YUV440P12BE
#158	constant AV_PIX_FMT_AYUV64LE
#159	constant AV_PIX_FMT_AYUV64BE
#160	constant AV_PIX_FMT_VIDEOTOOLBOX
#161	constant AV_PIX_FMT_P010LE
#162	constant AV_PIX_FMT_P010BE
#163	constant AV_PIX_FMT_GBRAP12BE
#164	constant AV_PIX_FMT_GBRAP12LE
#165	constant AV_PIX_FMT_GBRAP10BE
#166	constant AV_PIX_FMT_GBRAP10LE
#167	constant AV_PIX_FMT_MEDIACODEC
#168	constant AV_PIX_FMT_GRAY12BE
#169	constant AV_PIX_FMT_GRAY12LE
#170	constant AV_PIX_FMT_GRAY10BE
#171	constant AV_PIX_FMT_GRAY10LE
#172	constant AV_PIX_FMT_P016LE
#173	constant AV_PIX_FMT_P016BE
#174	constant AV_PIX_FMT_D3D11
#175	constant AV_PIX_FMT_GRAY9BE
#176	constant AV_PIX_FMT_GRAY9LE
#177	constant AV_PIX_FMT_GBRPF32BE
#178	constant AV_PIX_FMT_GBRPF32LE
#179	constant AV_PIX_FMT_GBRAPF32BE
#180	constant AV_PIX_FMT_GBRAPF32LE
#181	constant AV_PIX_FMT_DRM_PRIME
#182	constant AV_PIX_FMT_OPENCL
#183	constant AV_PIX_FMT_GRAY14BE
#184	constant AV_PIX_FMT_GRAY14LE
#185	constant AV_PIX_FMT_GRAYF32BE
#186	constant AV_PIX_FMT_GRAYF32LE
#187	constant AV_PIX_FMT_YUVA422P12BE
#188	constant AV_PIX_FMT_YUVA422P12LE
#189	constant AV_PIX_FMT_YUVA444P12BE
#190	constant AV_PIX_FMT_YUVA444P12LE
#191	constant AV_PIX_FMT_NV24
#192	constant AV_PIX_FMT_NV42
#193	constant AV_PIX_FMT_NB
#0	constant AVCOL_PRI_RESERVED0
#1	constant AVCOL_PRI_BT709
#2	constant AVCOL_PRI_UNSPECIFIED
#3	constant AVCOL_PRI_RESERVED
#4	constant AVCOL_PRI_BT470M
#5	constant AVCOL_PRI_BT470BG
#6	constant AVCOL_PRI_SMPTE170M
#7	constant AVCOL_PRI_SMPTE240M
#8	constant AVCOL_PRI_FILM
#9	constant AVCOL_PRI_BT2020
#10	constant AVCOL_PRI_SMPTE428
#10	constant AVCOL_PRI_SMPTEST428_1
#11	constant AVCOL_PRI_SMPTE431
#12	constant AVCOL_PRI_SMPTE432
#22	constant AVCOL_PRI_JEDEC_P22
#23	constant AVCOL_PRI_NB
#0	constant AVCOL_TRC_RESERVED0
#1	constant AVCOL_TRC_BT709
#2	constant AVCOL_TRC_UNSPECIFIED
#3	constant AVCOL_TRC_RESERVED
#4	constant AVCOL_TRC_GAMMA22
#5	constant AVCOL_TRC_GAMMA28
#6	constant AVCOL_TRC_SMPTE170M
#7	constant AVCOL_TRC_SMPTE240M
#8	constant AVCOL_TRC_LINEAR
#9	constant AVCOL_TRC_LOG
#10	constant AVCOL_TRC_LOG_SQRT
#11	constant AVCOL_TRC_IEC61966_2_4
#12	constant AVCOL_TRC_BT1361_ECG
#13	constant AVCOL_TRC_IEC61966_2_1
#14	constant AVCOL_TRC_BT2020_10
#15	constant AVCOL_TRC_BT2020_12
#16	constant AVCOL_TRC_SMPTE2084
#16	constant AVCOL_TRC_SMPTEST2084
#17	constant AVCOL_TRC_SMPTE428
#17	constant AVCOL_TRC_SMPTEST428_1
#18	constant AVCOL_TRC_ARIB_STD_B67
#19	constant AVCOL_TRC_NB
#0	constant AVCOL_SPC_RGB
#1	constant AVCOL_SPC_BT709
#2	constant AVCOL_SPC_UNSPECIFIED
#3	constant AVCOL_SPC_RESERVED
#4	constant AVCOL_SPC_FCC
#5	constant AVCOL_SPC_BT470BG
#6	constant AVCOL_SPC_SMPTE170M
#7	constant AVCOL_SPC_SMPTE240M
#8	constant AVCOL_SPC_YCGCO
#8	constant AVCOL_SPC_YCOCG
#9	constant AVCOL_SPC_BT2020_NCL
#10	constant AVCOL_SPC_BT2020_CL
#11	constant AVCOL_SPC_SMPTE2085
#12	constant AVCOL_SPC_CHROMA_DERIVED_NCL
#13	constant AVCOL_SPC_CHROMA_DERIVED_CL
#14	constant AVCOL_SPC_ICTCP
#15	constant AVCOL_SPC_NB
#0	constant AVCOL_RANGE_UNSPECIFIED
#1	constant AVCOL_RANGE_MPEG
#2	constant AVCOL_RANGE_JPEG
#3	constant AVCOL_RANGE_NB
#0	constant AVCHROMA_LOC_UNSPECIFIED
#1	constant AVCHROMA_LOC_LEFT
#2	constant AVCHROMA_LOC_CENTER
#3	constant AVCHROMA_LOC_TOPLEFT
#4	constant AVCHROMA_LOC_TOP
#5	constant AVCHROMA_LOC_BOTTOMLEFT
#6	constant AVCHROMA_LOC_BOTTOM
#7	constant AVCHROMA_LOC_NB

\ -------===< structs >===--------
\ AVCodecDescriptor
begin-structure AVCodecDescriptor
	drop 8 8 +field AVCodecDescriptor-name
	drop 0 4 +field AVCodecDescriptor-id
	drop 24 4 +field AVCodecDescriptor-props
	drop 32 8 +field AVCodecDescriptor-mime_types
	drop 4 4 +field AVCodecDescriptor-type
	drop 16 8 +field AVCodecDescriptor-long_name
	drop 40 8 +field AVCodecDescriptor-profiles
drop 48 end-structure
\ RcOverride
begin-structure RcOverride
	drop 12 4 +field RcOverride-quality_factor
	drop 8 4 +field RcOverride-qscale
	drop 0 4 +field RcOverride-start_frame
	drop 4 4 +field RcOverride-end_frame
drop 16 end-structure
\ AVPanScan
begin-structure AVPanScan
	drop 12 12 +field AVPanScan-position
	drop 0 4 +field AVPanScan-id
	drop 8 4 +field AVPanScan-height
	drop 4 4 +field AVPanScan-width
drop 24 end-structure
\ AVCPBProperties
begin-structure AVCPBProperties
	drop 12 4 +field AVCPBProperties-buffer_size
	drop 16 8 +field AVCPBProperties-vbv_delay
	drop 0 8 +field AVCPBProperties-max_bitrate
	drop 4 8 +field AVCPBProperties-min_bitrate
	drop 8 8 +field AVCPBProperties-avg_bitrate
drop 24 end-structure
\ AVPacketSideData
begin-structure AVPacketSideData
	drop 0 8 +field AVPacketSideData-data
	drop 8 4 +field AVPacketSideData-size
	drop 12 4 +field AVPacketSideData-type
drop 16 end-structure
\ AVPacket
begin-structure AVPacket
	drop 48 8 +field AVPacket-side_data
	drop 24 8 +field AVPacket-data
	drop 16 8 +field AVPacket-dts
	drop 64 8 +field AVPacket-duration
	drop 0 8 +field AVPacket-buf
	drop 56 4 +field AVPacket-side_data_elems
	drop 32 4 +field AVPacket-size
	drop 8 8 +field AVPacket-pts
	drop 40 4 +field AVPacket-flags
	drop 36 4 +field AVPacket-stream_index
	drop 72 8 +field AVPacket-pos
drop 88 end-structure
\ AVCodecContext
begin-structure AVCodecContext
	drop 640 4 +field AVCodecContext-workaround_bugs
	drop 120 4 +field AVCodecContext-height
	drop 480 4 +field AVCodecContext-qmax
	drop 484 4 +field AVCodecContext-max_qdiff
	drop 816 4 +field AVCodecContext-nsse_weight
	drop 624 8 +field AVCodecContext-stats_out
	drop 452 4 +field AVCodecContext-request_sample_fmt
	drop 408 4 +field AVCodecContext-sample_fmt
	drop 412 4 +field AVCodecContext-frame_size
	drop 632 8 +field AVCodecContext-stats_in
	drop 884 8 +field AVCodecContext-pkt_timebase
	drop 472 4 +field AVCodecContext-qblur
	drop 820 4 +field AVCodecContext-profile
	drop 388 4 +field AVCodecContext-chroma_sample_location
	drop 32 8 +field AVCodecContext-priv_data
	drop 828 4 +field AVCodecContext-skip_loop_filter
	drop 416 4 +field AVCodecContext-frame_number
	drop 896 8 +field AVCodecContext-codec_descriptor
	drop 380 4 +field AVCodecContext-colorspace
	drop 904 8 +field AVCodecContext-pts_correction_num_faulty_pts
	drop 840 8 +field AVCodecContext-subtitle_header
	drop 64 4 +field AVCodecContext-bit_rate_tolerance
	drop 252 4 +field AVCodecContext-ildct_cmp
	drop 792 4 +field AVCodecContext-active_thread_type
	drop 788 4 +field AVCodecContext-thread_type
	drop 372 4 +field AVCodecContext-color_primaries
	drop 456 8 +field AVCodecContext-get_buffer2
	drop 644 4 +field AVCodecContext-strict_std_compliance
	drop 16 8 +field AVCodecContext-codec
	drop 524 4 +field AVCodecContext-rc_min_vbv_overflow_use
	drop 512 8 +field AVCodecContext-rc_min_rate
	drop 1000 4 +field AVCodecContext-nb_coded_side_data
	drop 992 8 +field AVCodecContext-coded_side_data
	drop 672 8 +field AVCodecContext-hwaccel
	drop 928 8 +field AVCodecContext-pts_correction_last_dts
	drop 1008 8 +field AVCodecContext-hw_frames_ctx
	drop 688 64 +field AVCodecContext-error
	drop 68 4 +field AVCodecContext-global_quality
	drop 276 4 +field AVCodecContext-me_subpel_quality
	drop 404 4 +field AVCodecContext-channels
	drop 284 4 +field AVCodecContext-slice_flags
	drop 280 4 +field AVCodecContext-me_range
	drop 848 4 +field AVCodecContext-subtitle_header_size
	drop 488 4 +field AVCodecContext-rc_buffer_size
	drop 504 8 +field AVCodecContext-rc_max_rate
	drop 952 4 +field AVCodecContext-seek_preroll
	drop 256 4 +field AVCodecContext-dia_size
	drop 272 4 +field AVCodecContext-pre_dia_size
	drop 768 4 +field AVCodecContext-lowres
	drop 124 4 +field AVCodecContext-coded_width
	drop 188 4 +field AVCodecContext-i_quant_offset
	drop 172 4 +field AVCodecContext-b_quant_offset
	drop 8 4 +field AVCodecContext-log_level_offset
	drop 224 8 +field AVCodecContext-slice_offset
	drop 832 4 +field AVCodecContext-skip_idct
	drop 364 4 +field AVCodecContext-mv0_threshold
	drop 332 4 +field AVCodecContext-mb_lmin
	drop 1016 4 +field AVCodecContext-sub_text_format
	drop 152 8 +field AVCodecContext-get_format
	drop 192 4 +field AVCodecContext-lumi_masking
	drop 196 4 +field AVCodecContext-temporal_cplx_masking
	drop 200 4 +field AVCodecContext-spatial_cplx_masking
	drop 204 4 +field AVCodecContext-p_masking
	drop 208 4 +field AVCodecContext-dark_masking
	drop 800 8 +field AVCodecContext-execute
	drop 880 4 +field AVCodecContext-sw_pix_fmt
	drop 136 4 +field AVCodecContext-pix_fmt
	drop 680 8 +field AVCodecContext-hwaccel_context
	drop 1040 4 +field AVCodecContext-hwaccel_flags
	drop 656 4 +field AVCodecContext-err_recognition
	drop 496 8 +field AVCodecContext-rc_override
	drop 492 4 +field AVCodecContext-rc_override_count
	drop 212 4 +field AVCodecContext-slice_count
	drop 384 4 +field AVCodecContext-color_range
	drop 652 4 +field AVCodecContext-debug
	drop 476 4 +field AVCodecContext-qmin
	drop 344 4 +field AVCodecContext-bidir_refine
	drop 112 4 +field AVCodecContext-delay
	drop 144 8 +field AVCodecContext-draw_horiz_band
	drop 328 4 +field AVCodecContext-skip_bottom
	drop 96 4 +field AVCodecContext-extradata_size
	drop 1044 4 +field AVCodecContext-apply_cropping
	drop 664 8 +field AVCodecContext-reordered_opaque
	drop 944 4 +field AVCodecContext-sub_charenc_mode
	drop 80 4 +field AVCodecContext-flags2
	drop 132 4 +field AVCodecContext-gop_size
	drop 468 4 +field AVCodecContext-qcompress
	drop 240 4 +field AVCodecContext-me_cmp
	drop 648 4 +field AVCodecContext-error_concealment
	drop 88 8 +field AVCodecContext-extradata
	drop 352 4 +field AVCodecContext-keyint_min
	drop 976 8 +field AVCodecContext-codec_whitelist
	drop 448 4 +field AVCodecContext-audio_service_type
	drop 248 4 +field AVCodecContext-mb_cmp
	drop 268 4 +field AVCodecContext-me_pre_cmp
	drop 1048 4 +field AVCodecContext-extra_hw_frames
	drop 464 4 +field AVCodecContext-refcounted_frames
	drop 176 4 +field AVCodecContext-has_b_frames
	drop 160 4 +field AVCodecContext-max_b_frames
	drop 960 8 +field AVCodecContext-chroma_intra_matrix
	drop 296 8 +field AVCodecContext-intra_matrix
	drop 304 8 +field AVCodecContext-inter_matrix
	drop 72 4 +field AVCodecContext-compression_level
	drop 420 4 +field AVCodecContext-block_align
	drop 784 4 +field AVCodecContext-thread_count
	drop 260 4 +field AVCodecContext-last_predictor_count
	drop 232 8 +field AVCodecContext-sample_aspect_ratio
	drop 1020 4 +field AVCodecContext-trailing_padding
	drop 868 4 +field AVCodecContext-initial_padding
	drop 116 4 +field AVCodecContext-width
	drop 968 8 +field AVCodecContext-dump_separator
	drop 392 4 +field AVCodecContext-slices
	drop 920 8 +field AVCodecContext-pts_correction_last_pts
	drop 936 8 +field AVCodecContext-sub_charenc
	drop 28 4 +field AVCodecContext-codec_tag
	drop 48 8 +field AVCodecContext-opaque
	drop 400 4 +field AVCodecContext-sample_rate
	drop 356 4 +field AVCodecContext-refs
	drop 76 4 +field AVCodecContext-flags
	drop 1024 8 +field AVCodecContext-max_pixels
	drop 56 8 +field AVCodecContext-bit_rate
	drop 1032 8 +field AVCodecContext-hw_device_ctx
	drop 872 8 +field AVCodecContext-framerate
	drop 836 4 +field AVCodecContext-skip_frame
	drop 108 4 +field AVCodecContext-ticks_per_frame
	drop 912 8 +field AVCodecContext-pts_correction_num_faulty_dts
	drop 956 4 +field AVCodecContext-debug_mv
	drop 40 8 +field AVCodecContext-internal
	drop 528 4 +field AVCodecContext-rc_initial_buffer_occupancy
	drop 424 4 +field AVCodecContext-cutoff
	drop 324 4 +field AVCodecContext-skip_top
	drop 244 4 +field AVCodecContext-me_sub_cmp
	drop 12 4 +field AVCodecContext-codec_type
	drop 764 4 +field AVCodecContext-bits_per_raw_sample
	drop 760 4 +field AVCodecContext-bits_per_coded_sample
	drop 556 4 +field AVCodecContext-trellis
	drop 1052 4 +field AVCodecContext-discard_damaged_percentage
	drop 756 4 +field AVCodecContext-idct_algo
	drop 752 4 +field AVCodecContext-dct_algo
	drop 984 4 +field AVCodecContext-properties
	drop 128 4 +field AVCodecContext-coded_height
	drop 808 8 +field AVCodecContext-execute2
	drop 24 4 +field AVCodecContext-codec_id
	drop 376 4 +field AVCodecContext-color_trc
	drop 440 8 +field AVCodecContext-request_channel_layout
	drop 432 8 +field AVCodecContext-channel_layout
	drop 100 8 +field AVCodecContext-time_base
	drop 948 4 +field AVCodecContext-skip_alpha
	drop 0 8 +field AVCodecContext-av_class
	drop 824 4 +field AVCodecContext-level
	drop 796 4 +field AVCodecContext-thread_safe_callbacks
	drop 336 4 +field AVCodecContext-mb_lmax
	drop 288 4 +field AVCodecContext-mb_decision
	drop 320 4 +field AVCodecContext-intra_dc_precision
	drop 520 4 +field AVCodecContext-rc_max_available_vbv_use
	drop 396 4 +field AVCodecContext-field_order
	drop 184 4 +field AVCodecContext-i_quant_factor
	drop 164 4 +field AVCodecContext-b_quant_factor
drop 1056 end-structure
\ AVProfile
begin-structure AVProfile
	drop 8 8 +field AVProfile-name
	drop 0 4 +field AVProfile-profile
drop 16 end-structure
\ AVCodecHWConfig
begin-structure AVCodecHWConfig
	drop 8 4 +field AVCodecHWConfig-device_type
	drop 0 4 +field AVCodecHWConfig-pix_fmt
	drop 4 4 +field AVCodecHWConfig-methods
drop 12 end-structure
\ AVCodec
begin-structure AVCodec
	drop 40 8 +field AVCodec-pix_fmts
	drop 176 8 +field AVCodec-decode
	drop 80 8 +field AVCodec-priv_class
	drop 48 8 +field AVCodec-supported_samplerates
	drop 64 8 +field AVCodec-channel_layouts
	drop 8 8 +field AVCodec-long_name
	drop 0 8 +field AVCodec-name
	drop 128 8 +field AVCodec-update_thread_context
	drop 168 8 +field AVCodec-encode2
	drop 208 8 +field AVCodec-receive_frame
	drop 24 4 +field AVCodec-capabilities
	drop 216 8 +field AVCodec-flush
	drop 120 8 +field AVCodec-init_thread_copy
	drop 224 4 +field AVCodec-caps_internal
	drop 88 8 +field AVCodec-profiles
	drop 32 8 +field AVCodec-supported_framerates
	drop 104 4 +field AVCodec-priv_data_size
	drop 136 8 +field AVCodec-defaults
	drop 56 8 +field AVCodec-sample_fmts
	drop 20 4 +field AVCodec-id
	drop 72 1 +field AVCodec-max_lowres
	drop 144 8 +field AVCodec-init_static_data
	drop 16 4 +field AVCodec-type
	drop 240 8 +field AVCodec-hw_configs
	drop 96 8 +field AVCodec-wrapper_name
	drop 112 8 +field AVCodec-next
	drop 200 8 +field AVCodec-receive_packet
	drop 232 8 +field AVCodec-bsfs
	drop 160 8 +field AVCodec-encode_sub
	drop 184 8 +field AVCodec-close
	drop 152 8 +field AVCodec-init
	drop 192 8 +field AVCodec-send_frame
drop 248 end-structure
\ AVHWAccel
begin-structure AVHWAccel
	drop 16 4 +field AVHWAccel-pix_fmt
	drop 24 8 +field AVHWAccel-alloc_frame
	drop 0 8 +field AVHWAccel-name
	drop 20 4 +field AVHWAccel-capabilities
	drop 48 8 +field AVHWAccel-decode_slice
	drop 40 8 +field AVHWAccel-decode_params
	drop 104 8 +field AVHWAccel-frame_params
	drop 100 4 +field AVHWAccel-caps_internal
	drop 64 4 +field AVHWAccel-frame_priv_data_size
	drop 96 4 +field AVHWAccel-priv_data_size
	drop 12 4 +field AVHWAccel-id
	drop 8 4 +field AVHWAccel-type
	drop 72 8 +field AVHWAccel-decode_mb
	drop 88 8 +field AVHWAccel-uninit
	drop 56 8 +field AVHWAccel-end_frame
	drop 32 8 +field AVHWAccel-start_frame
	drop 80 8 +field AVHWAccel-init
drop 112 end-structure
\ AVSubtitleRect
begin-structure AVSubtitleRect
	drop 8 4 +field AVSubtitleRect-w
	drop 16 4 +field AVSubtitleRect-nb_colors
	drop 0 4 +field AVSubtitleRect-x
	drop 120 32 +field AVSubtitleRect-data
	drop 4 4 +field AVSubtitleRect-y
	drop 152 16 +field AVSubtitleRect-linesize
	drop 168 4 +field AVSubtitleRect-type
	drop 176 8 +field AVSubtitleRect-text
	drop 192 4 +field AVSubtitleRect-flags
	drop 12 4 +field AVSubtitleRect-h
	drop 184 8 +field AVSubtitleRect-ass
drop 200 end-structure
\ AVSubtitle
begin-structure AVSubtitle
	drop 12 4 +field AVSubtitle-num_rects
	drop 16 8 +field AVSubtitle-rects
	drop 0 2 +field AVSubtitle-format
	drop 4 4 +field AVSubtitle-start_display_time
	drop 8 4 +field AVSubtitle-end_display_time
	drop 24 8 +field AVSubtitle-pts
drop 32 end-structure
\ AVCodecParameters
begin-structure AVCodecParameters
	drop 16 8 +field AVCodecParameters-extradata
	drop 76 4 +field AVCodecParameters-color_range
	drop 136 4 +field AVCodecParameters-seek_preroll
	drop 60 4 +field AVCodecParameters-height
	drop 92 4 +field AVCodecParameters-chroma_location
	drop 124 4 +field AVCodecParameters-frame_size
	drop 32 8 +field AVCodecParameters-bit_rate
	drop 116 4 +field AVCodecParameters-sample_rate
	drop 48 4 +field AVCodecParameters-profile
	drop 88 4 +field AVCodecParameters-color_space
	drop 28 4 +field AVCodecParameters-format
	drop 52 4 +field AVCodecParameters-level
	drop 0 4 +field AVCodecParameters-codec_type
	drop 120 4 +field AVCodecParameters-block_align
	drop 24 4 +field AVCodecParameters-extradata_size
	drop 112 4 +field AVCodecParameters-channels
	drop 56 4 +field AVCodecParameters-width
	drop 96 4 +field AVCodecParameters-video_delay
	drop 64 8 +field AVCodecParameters-sample_aspect_ratio
	drop 8 4 +field AVCodecParameters-codec_tag
	drop 80 4 +field AVCodecParameters-color_primaries
	drop 128 4 +field AVCodecParameters-initial_padding
	drop 132 4 +field AVCodecParameters-trailing_padding
	drop 44 4 +field AVCodecParameters-bits_per_raw_sample
	drop 40 4 +field AVCodecParameters-bits_per_coded_sample
	drop 4 4 +field AVCodecParameters-codec_id
	drop 72 4 +field AVCodecParameters-field_order
	drop 84 4 +field AVCodecParameters-color_trc
	drop 104 8 +field AVCodecParameters-channel_layout
drop 144 end-structure
\ AVCodecParserContext
begin-structure AVCodecParserContext
	drop 56 8 +field AVCodecParserContext-dts
	drop 40 4 +field AVCodecParserContext-pict_type
	drop 344 4 +field AVCodecParserContext-format
	drop 328 4 +field AVCodecParserContext-width
	drop 48 8 +field AVCodecParserContext-pts
	drop 152 32 +field AVCodecParserContext-cur_frame_dts
	drop 80 4 +field AVCodecParserContext-fetch_timestamp
	drop 200 32 +field AVCodecParserContext-cur_frame_end
	drop 312 4 +field AVCodecParserContext-duration
	drop 0 8 +field AVCodecParserContext-priv_data
	drop 120 32 +field AVCodecParserContext-cur_frame_pts
	drop 324 4 +field AVCodecParserContext-output_picture_number
	drop 256 4 +field AVCodecParserContext-pts_dts_delta
	drop 252 4 +field AVCodecParserContext-dts_ref_dts_delta
	drop 340 4 +field AVCodecParserContext-coded_height
	drop 320 4 +field AVCodecParserContext-picture_structure
	drop 8 8 +field AVCodecParserContext-parser
	drop 304 8 +field AVCodecParserContext-last_pos
	drop 248 4 +field AVCodecParserContext-dts_sync_point
	drop 316 4 +field AVCodecParserContext-field_order
	drop 332 4 +field AVCodecParserContext-height
	drop 16 8 +field AVCodecParserContext-frame_offset
	drop 24 8 +field AVCodecParserContext-cur_offset
	drop 32 8 +field AVCodecParserContext-next_frame_offset
	drop 88 32 +field AVCodecParserContext-cur_frame_offset
	drop 72 8 +field AVCodecParserContext-last_dts
	drop 296 8 +field AVCodecParserContext-pos
	drop 184 4 +field AVCodecParserContext-flags
	drop 232 4 +field AVCodecParserContext-key_frame
	drop 44 4 +field AVCodecParserContext-repeat_pict
	drop 336 4 +field AVCodecParserContext-coded_width
	drop 64 8 +field AVCodecParserContext-last_pts
	drop 264 32 +field AVCodecParserContext-cur_frame_pos
	drop 84 4 +field AVCodecParserContext-cur_frame_start_index
	drop 192 8 +field AVCodecParserContext-offset
drop 352 end-structure
\ AVCodecParser
begin-structure AVCodecParser
	drop 48 8 +field AVCodecParser-split
	drop 0 20 +field AVCodecParser-codec_ids
	drop 20 4 +field AVCodecParser-priv_data_size
	drop 24 8 +field AVCodecParser-parser_init
	drop 32 8 +field AVCodecParser-parser_parse
	drop 40 8 +field AVCodecParser-parser_close
	drop 56 8 +field AVCodecParser-next
drop 64 end-structure
\ AVBSFContext
begin-structure AVBSFContext
	drop 16 8 +field AVBSFContext-internal
	drop 32 8 +field AVBSFContext-par_in
	drop 40 8 +field AVBSFContext-par_out
	drop 8 8 +field AVBSFContext-filter
	drop 48 8 +field AVBSFContext-time_base_in
	drop 0 8 +field AVBSFContext-av_class
	drop 24 8 +field AVBSFContext-priv_data
	drop 56 8 +field AVBSFContext-time_base_out
drop 64 end-structure
\ AVBitStreamFilter
begin-structure AVBitStreamFilter
	drop 32 8 +field AVBitStreamFilter-init
	drop 0 8 +field AVBitStreamFilter-name
	drop 8 8 +field AVBitStreamFilter-codec_ids
	drop 24 4 +field AVBitStreamFilter-priv_data_size
	drop 40 8 +field AVBitStreamFilter-filter
	drop 16 8 +field AVBitStreamFilter-priv_class
	drop 56 8 +field AVBitStreamFilter-flush
	drop 48 8 +field AVBitStreamFilter-close
drop 64 end-structure

\ --===< function pointers >===---
c-funptr AVCodecContext-draw_horiz_band() {((struct AVCodecContext*)ptr)->draw_horiz_band} a a a n n n -- void	( s src offset y type height -- )
c-funptr AVCodecContext-get_format() {((struct AVCodecContext*)ptr)->get_format} a a -- n	( s fmt -- )
c-funptr AVCodecContext-get_buffer2() {((struct AVCodecContext*)ptr)->get_buffer2} a a n -- n	( s frame flags -- )
c-funptr AVCodecContext-execute() {((struct AVCodecContext*)ptr)->execute} a a a a n n -- n	( c func arg2 ret count size -- )
c-funptr AVCodecContext-execute2() {((struct AVCodecContext*)ptr)->execute2} a a a a n -- n	( c func arg2 ret count -- )
c-funptr AVCodec-init_thread_copy() {((struct AVCodec*)ptr)->init_thread_copy} a -- n	( <noname> -- )
c-funptr AVCodec-update_thread_context() {((struct AVCodec*)ptr)->update_thread_context} a a -- n	( dst src -- )
c-funptr AVCodec-init_static_data() {((struct AVCodec*)ptr)->init_static_data} a -- void	( codec -- )
c-funptr AVCodec-init() {((struct AVCodec*)ptr)->init} a -- n	( <noname> -- )
c-funptr AVCodec-encode_sub() {((struct AVCodec*)ptr)->encode_sub} a a n a -- n	( <noname> buf buf_size sub -- )
c-funptr AVCodec-encode2() {((struct AVCodec*)ptr)->encode2} a a a a -- n	( avctx avpkt frame got_packet_ptr -- )
c-funptr AVCodec-decode() {((struct AVCodec*)ptr)->decode} a a a a -- n	( <noname> outdata outdata_size avpkt -- )
c-funptr AVCodec-close() {((struct AVCodec*)ptr)->close} a -- n	( <noname> -- )
c-funptr AVCodec-send_frame() {((struct AVCodec*)ptr)->send_frame} a a -- n	( avctx frame -- )
c-funptr AVCodec-receive_packet() {((struct AVCodec*)ptr)->receive_packet} a a -- n	( avctx avpkt -- )
c-funptr AVCodec-receive_frame() {((struct AVCodec*)ptr)->receive_frame} a a -- n	( avctx frame -- )
c-funptr AVCodec-flush() {((struct AVCodec*)ptr)->flush} a -- void	( <noname> -- )
c-funptr AVHWAccel-alloc_frame() {((struct AVHWAccel*)ptr)->alloc_frame} a a -- n	( avctx frame -- )
c-funptr AVHWAccel-start_frame() {((struct AVHWAccel*)ptr)->start_frame} a a n -- n	( avctx buf buf_size -- )
c-funptr AVHWAccel-decode_params() {((struct AVHWAccel*)ptr)->decode_params} a n a n -- n	( avctx type buf buf_size -- )
c-funptr AVHWAccel-decode_slice() {((struct AVHWAccel*)ptr)->decode_slice} a a n -- n	( avctx buf buf_size -- )
c-funptr AVHWAccel-end_frame() {((struct AVHWAccel*)ptr)->end_frame} a -- n	( avctx -- )
c-funptr AVHWAccel-decode_mb() {((struct AVHWAccel*)ptr)->decode_mb} a -- void	( s -- )
c-funptr AVHWAccel-init() {((struct AVHWAccel*)ptr)->init} a -- n	( avctx -- )
c-funptr AVHWAccel-uninit() {((struct AVHWAccel*)ptr)->uninit} a -- n	( avctx -- )
c-funptr AVHWAccel-frame_params() {((struct AVHWAccel*)ptr)->frame_params} a a -- n	( avctx hw_frames_ctx -- )
c-funptr AVCodecParser-parser_init() {((struct AVCodecParser*)ptr)->parser_init} a -- n	( s -- )
c-funptr AVCodecParser-parser_parse() {((struct AVCodecParser*)ptr)->parser_parse} a a a a a n -- n	( s avctx poutbuf poutbuf_size buf buf_size -- )
c-funptr AVCodecParser-parser_close() {((struct AVCodecParser*)ptr)->parser_close} a -- void	( s -- )
c-funptr AVCodecParser-split() {((struct AVCodecParser*)ptr)->split} a a n -- n	( avctx buf buf_size -- )
c-funptr AVBitStreamFilter-init() {((struct AVBitStreamFilter*)ptr)->init} a -- n	( ctx -- )
c-funptr AVBitStreamFilter-filter() {((struct AVBitStreamFilter*)ptr)->filter} a a -- n	( ctx pkt -- )
c-funptr AVBitStreamFilter-close() {((struct AVBitStreamFilter*)ptr)->close} a -- void	( ctx -- )
c-funptr AVBitStreamFilter-flush() {((struct AVBitStreamFilter*)ptr)->flush} a -- void	( ctx -- )

\ ------===< functions >===-------
c-function avcodec_get_hw_config avcodec_get_hw_config a n -- a	( codec index -- )
c-function av_codec_iterate av_codec_iterate a -- a	( opaque -- )
c-function avcodec_version avcodec_version  -- u	( -- )
c-function avcodec_configuration avcodec_configuration  -- s	( -- )
c-function avcodec_license avcodec_license  -- s	( -- )
c-function avcodec_alloc_context3 avcodec_alloc_context3 a -- a	( codec -- )
c-function avcodec_free_context avcodec_free_context a -- void	( avctx -- )
c-function avcodec_get_class avcodec_get_class  -- a	( -- )
c-function avcodec_parameters_alloc avcodec_parameters_alloc  -- a	( -- )
c-function avcodec_parameters_free avcodec_parameters_free a -- void	( par -- )
c-function avcodec_parameters_copy avcodec_parameters_copy a a -- n	( dst src -- )
c-function avcodec_parameters_from_context avcodec_parameters_from_context a a -- n	( par codec -- )
c-function avcodec_parameters_to_context avcodec_parameters_to_context a a -- n	( codec par -- )
c-function avcodec_open2 avcodec_open2 a a a -- n	( avctx codec options -- )
c-function avcodec_close avcodec_close a -- n	( avctx -- )
c-function avsubtitle_free avsubtitle_free a -- void	( sub -- )
c-function av_packet_alloc av_packet_alloc  -- a	( -- )
c-function av_packet_clone av_packet_clone a -- a	( src -- )
c-function av_packet_free av_packet_free a -- void	( pkt -- )
c-function av_init_packet av_init_packet a -- void	( pkt -- )
c-function av_new_packet av_new_packet a n -- n	( pkt size -- )
c-function av_shrink_packet av_shrink_packet a n -- void	( pkt size -- )
c-function av_grow_packet av_grow_packet a n -- n	( pkt grow_by -- )
c-function av_packet_from_data av_packet_from_data a a n -- n	( pkt data size -- )
c-function av_packet_new_side_data av_packet_new_side_data a n n -- a	( pkt type size -- )
c-function av_packet_add_side_data av_packet_add_side_data a n a n -- n	( pkt type data size -- )
c-function av_packet_shrink_side_data av_packet_shrink_side_data a n n -- n	( pkt type size -- )
c-function av_packet_get_side_data av_packet_get_side_data a n a -- a	( pkt type size -- )
c-function av_packet_side_data_name av_packet_side_data_name n -- s	( type -- )
c-function av_packet_pack_dictionary av_packet_pack_dictionary a a -- a	( dict size -- )
c-function av_packet_unpack_dictionary av_packet_unpack_dictionary a n a -- n	( data size dict -- )
c-function av_packet_free_side_data av_packet_free_side_data a -- void	( pkt -- )
c-function av_packet_ref av_packet_ref a a -- n	( dst src -- )
c-function av_packet_unref av_packet_unref a -- void	( pkt -- )
c-function av_packet_move_ref av_packet_move_ref a a -- void	( dst src -- )
c-function av_packet_copy_props av_packet_copy_props a a -- n	( dst src -- )
c-function av_packet_make_refcounted av_packet_make_refcounted a -- n	( pkt -- )
c-function av_packet_make_writable av_packet_make_writable a -- n	( pkt -- )
c-function av_packet_rescale_ts av_packet_rescale_ts a d d -- void	( pkt tb_src tb_dst -- )
c-function avcodec_find_decoder avcodec_find_decoder n -- a	( id -- )
c-function avcodec_find_decoder_by_name avcodec_find_decoder_by_name s -- a	( name -- )
c-function avcodec_default_get_buffer2 avcodec_default_get_buffer2 a a n -- n	( s frame flags -- )
c-function avcodec_align_dimensions avcodec_align_dimensions a a a -- void	( s width height -- )
c-function avcodec_align_dimensions2 avcodec_align_dimensions2 a a a a -- void	( s width height linesize_align -- )
c-function avcodec_enum_to_chroma_pos avcodec_enum_to_chroma_pos a a n -- n	( xpos ypos pos -- )
c-function avcodec_chroma_pos_to_enum avcodec_chroma_pos_to_enum n n -- n	( xpos ypos -- )
c-function avcodec_decode_audio4 avcodec_decode_audio4 a a a a -- n	( avctx frame got_frame_ptr avpkt -- )
c-function avcodec_decode_video2 avcodec_decode_video2 a a a a -- n	( avctx picture got_picture_ptr avpkt -- )
c-function avcodec_decode_subtitle2 avcodec_decode_subtitle2 a a a a -- n	( avctx sub got_sub_ptr avpkt -- )
c-function avcodec_send_packet avcodec_send_packet a a -- n	( avctx avpkt -- )
c-function avcodec_receive_frame avcodec_receive_frame a a -- n	( avctx frame -- )
c-function avcodec_send_frame avcodec_send_frame a a -- n	( avctx frame -- )
c-function avcodec_receive_packet avcodec_receive_packet a a -- n	( avctx avpkt -- )
c-function avcodec_get_hw_frames_parameters avcodec_get_hw_frames_parameters a a n a -- n	( avctx device_ref hw_pix_fmt out_frames_ref -- )
c-function av_parser_iterate av_parser_iterate a -- a	( opaque -- )
c-function av_parser_next av_parser_next a -- a	( c -- )
c-function av_register_codec_parser av_register_codec_parser a -- void	( parser -- )
c-function av_parser_init av_parser_init n -- a	( codec_id -- )
c-function av_parser_parse2 av_parser_parse2 a a a a a n n n n -- n	( s avctx poutbuf poutbuf_size buf buf_size pts dts pos -- )
c-function av_parser_change av_parser_change a a a a a n n -- n	( s avctx poutbuf poutbuf_size buf buf_size keyframe -- )
c-function av_parser_close av_parser_close a -- void	( s -- )
c-function avcodec_find_encoder avcodec_find_encoder n -- a	( id -- )
c-function avcodec_find_encoder_by_name avcodec_find_encoder_by_name s -- a	( name -- )
c-function avcodec_encode_audio2 avcodec_encode_audio2 a a a a -- n	( avctx avpkt frame got_packet_ptr -- )
c-function avcodec_encode_video2 avcodec_encode_video2 a a a a -- n	( avctx avpkt frame got_packet_ptr -- )
c-function avcodec_encode_subtitle avcodec_encode_subtitle a a n a -- n	( avctx buf buf_size sub -- )
c-function avcodec_pix_fmt_to_codec_tag avcodec_pix_fmt_to_codec_tag n -- u	( pix_fmt -- )
c-function avcodec_get_pix_fmt_loss avcodec_get_pix_fmt_loss n n n -- n	( dst_pix_fmt src_pix_fmt has_alpha -- )
c-function avcodec_find_best_pix_fmt_of_list avcodec_find_best_pix_fmt_of_list a n n a -- n	( pix_fmt_list src_pix_fmt has_alpha loss_ptr -- )
c-function avcodec_find_best_pix_fmt_of_2 avcodec_find_best_pix_fmt_of_2 n n n n a -- n	( dst_pix_fmt1 dst_pix_fmt2 src_pix_fmt has_alpha loss_ptr -- )
c-function avcodec_find_best_pix_fmt2 avcodec_find_best_pix_fmt2 n n n n a -- n	( dst_pix_fmt1 dst_pix_fmt2 src_pix_fmt has_alpha loss_ptr -- )
c-function avcodec_default_get_format avcodec_default_get_format a a -- n	( s fmt -- )
c-function avcodec_string avcodec_string a n a n -- void	( buf buf_size enc encode -- )
c-function av_get_profile_name av_get_profile_name a n -- s	( codec profile -- )
c-function avcodec_profile_name avcodec_profile_name n n -- s	( codec_id profile -- )
c-function avcodec_default_execute avcodec_default_execute a a a a n n -- n	( c func arg ret count size -- )
c-function avcodec_default_execute2 avcodec_default_execute2 a a a a n -- n	( c func arg ret count -- )
c-function avcodec_fill_audio_frame avcodec_fill_audio_frame a n n a n n -- n	( frame nb_channels sample_fmt buf buf_size align -- )
c-function avcodec_flush_buffers avcodec_flush_buffers a -- void	( avctx -- )
c-function av_get_bits_per_sample av_get_bits_per_sample n -- n	( codec_id -- )
c-function av_get_pcm_codec av_get_pcm_codec n n -- n	( fmt be -- )
c-function av_get_exact_bits_per_sample av_get_exact_bits_per_sample n -- n	( codec_id -- )
c-function av_get_audio_frame_duration av_get_audio_frame_duration a n -- n	( avctx frame_bytes -- )
c-function av_get_audio_frame_duration2 av_get_audio_frame_duration2 a n -- n	( par frame_bytes -- )
c-function av_bsf_get_by_name av_bsf_get_by_name s -- a	( name -- )
c-function av_bsf_iterate av_bsf_iterate a -- a	( opaque -- )
c-function av_bsf_alloc av_bsf_alloc a a -- n	( filter ctx -- )
c-function av_bsf_init av_bsf_init a -- n	( ctx -- )
c-function av_bsf_send_packet av_bsf_send_packet a a -- n	( ctx pkt -- )
c-function av_bsf_receive_packet av_bsf_receive_packet a a -- n	( ctx pkt -- )
c-function av_bsf_flush av_bsf_flush a -- void	( ctx -- )
c-function av_bsf_free av_bsf_free a -- void	( ctx -- )
c-function av_bsf_get_class av_bsf_get_class  -- a	( -- )
c-function av_bsf_list_alloc av_bsf_list_alloc  -- a	( -- )
c-function av_bsf_list_free av_bsf_list_free a -- void	( lst -- )
c-function av_bsf_list_append av_bsf_list_append a a -- n	( lst bsf -- )
c-function av_bsf_list_append2 av_bsf_list_append2 a s a -- n	( lst bsf_name options -- )
c-function av_bsf_list_finalize av_bsf_list_finalize a a -- n	( lst bsf -- )
c-function av_bsf_list_parse_str av_bsf_list_parse_str s a -- n	( str bsf -- )
c-function av_bsf_get_null_filter av_bsf_get_null_filter a -- n	( bsf -- )
c-function av_fast_padded_malloc av_fast_padded_malloc a a n -- void	( ptr size min_size -- )
c-function av_fast_padded_mallocz av_fast_padded_mallocz a a n -- void	( ptr size min_size -- )
c-function av_xiphlacing av_xiphlacing a u -- u	( s v -- )
c-function avcodec_get_type avcodec_get_type n -- n	( codec_id -- )
c-function avcodec_get_name avcodec_get_name n -- s	( id -- )
c-function avcodec_is_open avcodec_is_open a -- n	( s -- )
c-function av_codec_is_encoder av_codec_is_encoder a -- n	( codec -- )
c-function av_codec_is_decoder av_codec_is_decoder a -- n	( codec -- )
c-function avcodec_descriptor_get avcodec_descriptor_get n -- a	( id -- )
c-function avcodec_descriptor_next avcodec_descriptor_next a -- a	( prev -- )
c-function avcodec_descriptor_get_by_name avcodec_descriptor_get_by_name s -- a	( name -- )
c-function av_cpb_properties_alloc av_cpb_properties_alloc a -- a	( size -- )

\ ----===< postfix >===-----
end-c-library
