/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */
#include <stdio.h>
#include <string.h>
#include <stddef.h>

// Do not edit below this line
// end-of-default-includes


#include <SOIL2.h>
#ifdef __gnu_linux__
#undef stderr
extern struct _IO_FILE *stderr;
#endif

typedef enum{ NONE = -1, GFORTH = 0, SWIFTFORTH, VFX } SwigTargetSystem;
SwigTargetSystem swigTargetSystem = NONE;

unsigned char swigPrintStackComments = 1;

/* comments */
void swigNewline()
{
	printf( "\n" );
}

void swigComment( char *comment )
{
	printf( "\\ %s", comment );
}

/* generic print */
void swigPrint( char* gforth, char *swiftForth, char *vfx )
{
	if( swigTargetSystem == GFORTH )
		printf( "%s", gforth );
	else if( swigTargetSystem == SWIFTFORTH )
		printf( "%s", swiftForth );
	else if( swigTargetSystem == VFX )
		printf( "%s", vfx );
	printf( "\n" );
}
void swigPrintSystem( SwigTargetSystem targetSystem, char *text )
{
	if( targetSystem == swigTargetSystem )
	    printf( "%s\n", text );
}

/* constants */
void swigIntConstant( long constant, char *name )
{
	printf( "#%ld\tconstant %s\n", constant, name );
}

void swigUnsignedIntConstant( unsigned long constant, char *name )
{
	printf( "#%lu\tconstant %s\n", constant, name );
}

void swigLongConstant( long long constant, char *name )
{
	printf( "#%lld.\t2constant %s\n", constant, name );
}

void swigUnsignedLongConstant( unsigned long long constant, char *name )
{
	printf( "#%llu.\t2constant %s\n", constant, name );
}

void swigFloatConstant( double constant, char *name )
{
	char buffer[128];
	sprintf( buffer, "%f", constant );

	/* if the constant contains no exponent, add one */
	char *s;
	for( s = buffer; *s != 0; s++ )
		if( *s == 'e' || *s == 'E' )
			break;

	/* exponent found */
	if( *s != 0 )
		printf( "%s\tfconstant %s\n", buffer, name );
	/* not found */
	else
		printf( "%se0\tfconstant %s\n", buffer, name );
}

void swigStringConstant( char* constant, char *name )
{
	char c;
	printf( ": %s s\\\" ", name );
	while(( c = *constant++ ))
	{
		switch(c)
		{
			case '\b': printf( "\\b" ); break;
			case '\n': printf( "\\n" ); break;
			case '\f': printf( "\\f" ); break;
			case '\r': printf( "\\r" ); break;
			case '\t': printf( "\\t" ); break;
			case '"' : printf( "\\q" ); break;
			default:
				if(c < 0x20)
					printf("\\x%02x", c);
				else
					printf("%c", c); break;
		}
	}
	printf(	"\" ;\n" );
}

/* structs */
void swigStructField( char *name, size_t offset, size_t size )
{
	printf( "\tdrop %zu %zu +field %s\n", offset, size, name );
}

/* functions */
void swigFunction( char* gforth, char *swiftForth, char *vfx, char *stackComment )
{
	if( swigTargetSystem == GFORTH )
		printf( "%s", gforth );
	else if( swigTargetSystem == SWIFTFORTH )
		printf( "%s", swiftForth );
	else if( swigTargetSystem == VFX )
		printf( "%s", vfx );

	if( swigPrintStackComments )
		printf( "%s", stackComment );

	printf( "\n" );
}

/* function pointers */
void swigFunctionPointer( char* gforth, char *swiftForth, char *vfx, char *stackComment )
{
	swigFunction( gforth, swiftForth, vfx, stackComment );
}

/* callbacks */
void swigCallback( char* gforth, char *swiftForth, char *vfx, char *stackComment )
{
	swigFunction( gforth, swiftForth, vfx, stackComment );
}

void swigUsage( char **argv )
{
	fprintf( stderr, "Usage: %s [-gforth|-swiftforth|-vfx]\n", argv[0] );
}

int main( int argc, char **argv )
{
	int i;

	/* check arguments */
	for( i = 1; i < argc; i++ )
		if( strcmp( argv[i], "-gforth" ) == 0 )
			swigTargetSystem = GFORTH;
		else if( strcmp( argv[i], "-swiftforth" ) == 0 )
			swigTargetSystem = SWIFTFORTH;
		else if( strcmp( argv[i], "-vfx" ) == 0 )
			swigTargetSystem = VFX;

	if( swigTargetSystem == NONE )
	{
		fprintf( stderr, "Error: no target system specified\n" );
		swigUsage( argv );
		return 1;
	}

	/* primer */
	printf( "\\ This file has been generated using SWIG and fsi,\n"
		"\\ and is already platform dependent, search for the corresponding\n"
		"\\ fsi-file to compile it where no one has compiled it before ;)\n"
		"\\ Forth systems have their own own dynamic loader and don't need addional C-Code.\n"
		"\\ That's why this file will just print normal forth-code once compiled\n"
		"\\ and can be used directly with include or require.\n"
		"\\ As all comments are stripped during the compilation, please\n"
		"\\ insert the copyright notice of the original file here.\n"
	);



	swigNewline();

	swigComment("----===< prefix >===-----\n");

	swigPrint( "c-library soil2\ns\" soil2\" add-lib\n\\c #include <SOIL2.h>\n\\c #ifdef __gnu_linux__\n\\c #undef stderr\n\\c extern struct _IO_FILE *stderr;\n\\c #endif", "( none )", "( none )" );

	swigNewline();

	swigComment("--------===< enums >===---------\n");
	swigIntConstant( SOIL_LOAD_AUTO, "SOIL_LOAD_AUTO" );
	swigIntConstant( SOIL_LOAD_L, "SOIL_LOAD_L" );
	swigIntConstant( SOIL_LOAD_LA, "SOIL_LOAD_LA" );
	swigIntConstant( SOIL_LOAD_RGB, "SOIL_LOAD_RGB" );
	swigIntConstant( SOIL_LOAD_RGBA, "SOIL_LOAD_RGBA" );
	swigIntConstant( SOIL_CREATE_NEW_ID, "SOIL_CREATE_NEW_ID" );
	swigIntConstant( SOIL_FLAG_POWER_OF_TWO, "SOIL_FLAG_POWER_OF_TWO" );
	swigIntConstant( SOIL_FLAG_MIPMAPS, "SOIL_FLAG_MIPMAPS" );
	swigIntConstant( SOIL_FLAG_TEXTURE_REPEATS, "SOIL_FLAG_TEXTURE_REPEATS" );
	swigIntConstant( SOIL_FLAG_MULTIPLY_ALPHA, "SOIL_FLAG_MULTIPLY_ALPHA" );
	swigIntConstant( SOIL_FLAG_INVERT_Y, "SOIL_FLAG_INVERT_Y" );
	swigIntConstant( SOIL_FLAG_COMPRESS_TO_DXT, "SOIL_FLAG_COMPRESS_TO_DXT" );
	swigIntConstant( SOIL_FLAG_DDS_LOAD_DIRECT, "SOIL_FLAG_DDS_LOAD_DIRECT" );
	swigIntConstant( SOIL_FLAG_NTSC_SAFE_RGB, "SOIL_FLAG_NTSC_SAFE_RGB" );
	swigIntConstant( SOIL_FLAG_CoCg_Y, "SOIL_FLAG_CoCg_Y" );
	swigIntConstant( SOIL_FLAG_TEXTURE_RECTANGLE, "SOIL_FLAG_TEXTURE_RECTANGLE" );
	swigIntConstant( SOIL_FLAG_PVR_LOAD_DIRECT, "SOIL_FLAG_PVR_LOAD_DIRECT" );
	swigIntConstant( SOIL_FLAG_ETC1_LOAD_DIRECT, "SOIL_FLAG_ETC1_LOAD_DIRECT" );
	swigIntConstant( SOIL_FLAG_GL_MIPMAPS, "SOIL_FLAG_GL_MIPMAPS" );
	swigIntConstant( SOIL_FLAG_SRGB_COLOR_SPACE, "SOIL_FLAG_SRGB_COLOR_SPACE" );
	swigIntConstant( SOIL_SAVE_TYPE_TGA, "SOIL_SAVE_TYPE_TGA" );
	swigIntConstant( SOIL_SAVE_TYPE_BMP, "SOIL_SAVE_TYPE_BMP" );
	swigIntConstant( SOIL_SAVE_TYPE_PNG, "SOIL_SAVE_TYPE_PNG" );
	swigIntConstant( SOIL_SAVE_TYPE_DDS, "SOIL_SAVE_TYPE_DDS" );
	swigIntConstant( SOIL_SAVE_TYPE_JPG, "SOIL_SAVE_TYPE_JPG" );
	swigIntConstant( SOIL_HDR_RGBE, "SOIL_HDR_RGBE" );
	swigIntConstant( SOIL_HDR_RGBdivA, "SOIL_HDR_RGBdivA" );
	swigIntConstant( SOIL_HDR_RGBdivA2, "SOIL_HDR_RGBdivA2" );

	swigNewline();

	swigComment("------===< functions >===-------\n");
	swigFunction( "c-function SOIL_load_OGL_texture SOIL_load_OGL_texture s n u u -- u", "FUNCTION: SOIL_load_OGL_texture ( filename force_channels reuse_texture_ID flags -- u )", "EXTERN: \"C\" int SOIL_load_OGL_texture( char * filename, int force_channels, int reuse_texture_ID, int flags );", "	( filename force_channels reuse_texture_ID flags -- )" );
	swigFunction( "c-function SOIL_load_OGL_cubemap SOIL_load_OGL_cubemap s s s s s s n u u -- u", "FUNCTION: SOIL_load_OGL_cubemap ( x_pos_file x_neg_file y_pos_file y_neg_file z_pos_file z_neg_file force_channels reuse_texture_ID flags -- u )", "EXTERN: \"C\" int SOIL_load_OGL_cubemap( char * x_pos_file, char * x_neg_file, char * y_pos_file, char * y_neg_file, char * z_pos_file, char * z_neg_file, int force_channels, int reuse_texture_ID, int flags );", "	( x_pos_file x_neg_file y_pos_file y_neg_file z_pos_file z_neg_file force_channels reuse_texture_ID flags -- )" );
	swigFunction( "c-function SOIL_load_OGL_single_cubemap SOIL_load_OGL_single_cubemap s s n u u -- u", "FUNCTION: SOIL_load_OGL_single_cubemap ( filename face_order force_channels reuse_texture_ID flags -- u )", "EXTERN: \"C\" int SOIL_load_OGL_single_cubemap( char * filename, char * face_order, int force_channels, int reuse_texture_ID, int flags );", "	( filename face_order force_channels reuse_texture_ID flags -- )" );
	swigFunction( "c-function SOIL_load_OGL_HDR_texture SOIL_load_OGL_HDR_texture s n n u u -- u", "FUNCTION: SOIL_load_OGL_HDR_texture ( filename fake_HDR_format rescale_to_max reuse_texture_ID flags -- u )", "EXTERN: \"C\" int SOIL_load_OGL_HDR_texture( char * filename, int fake_HDR_format, int rescale_to_max, int reuse_texture_ID, int flags );", "	( filename fake_HDR_format rescale_to_max reuse_texture_ID flags -- )" );
	swigFunction( "c-function SOIL_load_OGL_texture_from_memory SOIL_load_OGL_texture_from_memory a n n u u -- u", "FUNCTION: SOIL_load_OGL_texture_from_memory ( buffer buffer_length force_channels reuse_texture_ID flags -- u )", "EXTERN: \"C\" int SOIL_load_OGL_texture_from_memory( void * buffer, int buffer_length, int force_channels, int reuse_texture_ID, int flags );", "	( buffer buffer_length force_channels reuse_texture_ID flags -- )" );
	swigFunction( "c-function SOIL_load_OGL_cubemap_from_memory SOIL_load_OGL_cubemap_from_memory a n a n a n a n a n a n n u u -- u", "FUNCTION: SOIL_load_OGL_cubemap_from_memory ( x_pos_buffer x_pos_buffer_length x_neg_buffer x_neg_buffer_length y_pos_buffer y_pos_buffer_length y_neg_buffer y_neg_buffer_length z_pos_buffer z_pos_buffer_length z_neg_buffer z_neg_buffer_length force_channels reuse_texture_ID flags -- u )", "EXTERN: \"C\" int SOIL_load_OGL_cubemap_from_memory( void * x_pos_buffer, int x_pos_buffer_length, void * x_neg_buffer, int x_neg_buffer_length, void * y_pos_buffer, int y_pos_buffer_length, void * y_neg_buffer, int y_neg_buffer_length, void * z_pos_buffer, int z_pos_buffer_length, void * z_neg_buffer, int z_neg_buffer_length, int force_channels, int reuse_texture_ID, int flags );", "	( x_pos_buffer x_pos_buffer_length x_neg_buffer x_neg_buffer_length y_pos_buffer y_pos_buffer_length y_neg_buffer y_neg_buffer_length z_pos_buffer z_pos_buffer_length z_neg_buffer z_neg_buffer_length force_channels reuse_texture_ID flags -- )" );
	swigFunction( "c-function SOIL_load_OGL_single_cubemap_from_memory SOIL_load_OGL_single_cubemap_from_memory a n s n u u -- u", "FUNCTION: SOIL_load_OGL_single_cubemap_from_memory ( buffer buffer_length face_order force_channels reuse_texture_ID flags -- u )", "EXTERN: \"C\" int SOIL_load_OGL_single_cubemap_from_memory( void * buffer, int buffer_length, char * face_order, int force_channels, int reuse_texture_ID, int flags );", "	( buffer buffer_length face_order force_channels reuse_texture_ID flags -- )" );
	swigFunction( "c-function SOIL_create_OGL_texture SOIL_create_OGL_texture a a a n u u -- u", "FUNCTION: SOIL_create_OGL_texture ( data width height channels reuse_texture_ID flags -- u )", "EXTERN: \"C\" int SOIL_create_OGL_texture( void * data, void * width, void * height, int channels, int reuse_texture_ID, int flags );", "	( data width height channels reuse_texture_ID flags -- )" );
	swigFunction( "c-function SOIL_create_OGL_single_cubemap SOIL_create_OGL_single_cubemap a n n n s u u -- u", "FUNCTION: SOIL_create_OGL_single_cubemap ( data width height channels face_order reuse_texture_ID flags -- u )", "EXTERN: \"C\" int SOIL_create_OGL_single_cubemap( void * data, int width, int height, int channels, char * face_order, int reuse_texture_ID, int flags );", "	( data width height channels face_order reuse_texture_ID flags -- )" );
	swigFunction( "c-function SOIL_save_screenshot SOIL_save_screenshot s n n n n n -- n", "FUNCTION: SOIL_save_screenshot ( filename image_type x y width height -- n )", "EXTERN: \"C\" int SOIL_save_screenshot( char * filename, int image_type, int x, int y, int width, int height );", "	( filename image_type x y width height -- )" );
	swigFunction( "c-function SOIL_load_image SOIL_load_image s a a a n -- a", "FUNCTION: SOIL_load_image ( filename width height channels force_channels -- a )", "EXTERN: \"C\" void * SOIL_load_image( char * filename, void * width, void * height, void * channels, int force_channels );", "	( filename width height channels force_channels -- )" );
	swigFunction( "c-function SOIL_load_image_from_memory SOIL_load_image_from_memory a n a a a n -- a", "FUNCTION: SOIL_load_image_from_memory ( buffer buffer_length width height channels force_channels -- a )", "EXTERN: \"C\" void * SOIL_load_image_from_memory( void * buffer, int buffer_length, void * width, void * height, void * channels, int force_channels );", "	( buffer buffer_length width height channels force_channels -- )" );
	swigFunction( "c-function SOIL_save_image_quality SOIL_save_image_quality s n n n n a n -- n", "FUNCTION: SOIL_save_image_quality ( filename image_type width height channels data quality -- n )", "EXTERN: \"C\" int SOIL_save_image_quality( char * filename, int image_type, int width, int height, int channels, void * data, int quality );", "	( filename image_type width height channels data quality -- )" );
	swigFunction( "c-function SOIL_save_image SOIL_save_image s n n n n a -- n", "FUNCTION: SOIL_save_image ( filename image_type width height channels data -- n )", "EXTERN: \"C\" int SOIL_save_image( char * filename, int image_type, int width, int height, int channels, void * data );", "	( filename image_type width height channels data -- )" );
	swigFunction( "c-function SOIL_free_image_data SOIL_free_image_data a -- void", "FUNCTION: SOIL_free_image_data ( img_data -- void )", "EXTERN: \"C\" void SOIL_free_image_data( void * img_data );", "	( img_data -- )" );
	swigFunction( "c-function SOIL_last_result SOIL_last_result  -- s", "FUNCTION: SOIL_last_result (  -- s )", "EXTERN: \"C\" char * SOIL_last_result(  );", "	( -- )" );
	swigFunction( "c-function SOIL_GL_GetProcAddress SOIL_GL_GetProcAddress s -- a", "FUNCTION: SOIL_GL_GetProcAddress ( proc -- a )", "EXTERN: \"C\" void * SOIL_GL_GetProcAddress( char * proc );", "	( proc -- )" );
	swigFunction( "c-function SOIL_GL_ExtensionSupported SOIL_GL_ExtensionSupported s -- n", "FUNCTION: SOIL_GL_ExtensionSupported ( extension -- n )", "EXTERN: \"C\" int SOIL_GL_ExtensionSupported( char * extension );", "	( extension -- )" );
	swigFunction( "c-function SOIL_direct_load_DDS SOIL_direct_load_DDS s u n n -- u", "FUNCTION: SOIL_direct_load_DDS ( filename reuse_texture_ID flags loading_as_cubemap -- u )", "EXTERN: \"C\" int SOIL_direct_load_DDS( char * filename, int reuse_texture_ID, int flags, int loading_as_cubemap );", "	( filename reuse_texture_ID flags loading_as_cubemap -- )" );
	swigFunction( "c-function SOIL_direct_load_DDS_from_memory SOIL_direct_load_DDS_from_memory a n u n n -- u", "FUNCTION: SOIL_direct_load_DDS_from_memory ( buffer buffer_length reuse_texture_ID flags loading_as_cubemap -- u )", "EXTERN: \"C\" int SOIL_direct_load_DDS_from_memory( void * buffer, int buffer_length, int reuse_texture_ID, int flags, int loading_as_cubemap );", "	( buffer buffer_length reuse_texture_ID flags loading_as_cubemap -- )" );
	swigFunction( "c-function SOIL_direct_load_PVR SOIL_direct_load_PVR s u n n -- u", "FUNCTION: SOIL_direct_load_PVR ( filename reuse_texture_ID flags loading_as_cubemap -- u )", "EXTERN: \"C\" int SOIL_direct_load_PVR( char * filename, int reuse_texture_ID, int flags, int loading_as_cubemap );", "	( filename reuse_texture_ID flags loading_as_cubemap -- )" );
	swigFunction( "c-function SOIL_direct_load_PVR_from_memory SOIL_direct_load_PVR_from_memory a n u n n -- u", "FUNCTION: SOIL_direct_load_PVR_from_memory ( buffer buffer_length reuse_texture_ID flags loading_as_cubemap -- u )", "EXTERN: \"C\" int SOIL_direct_load_PVR_from_memory( void * buffer, int buffer_length, int reuse_texture_ID, int flags, int loading_as_cubemap );", "	( buffer buffer_length reuse_texture_ID flags loading_as_cubemap -- )" );
	swigFunction( "c-function SOIL_direct_load_ETC1 SOIL_direct_load_ETC1 s u n -- u", "FUNCTION: SOIL_direct_load_ETC1 ( filename reuse_texture_ID flags -- u )", "EXTERN: \"C\" int SOIL_direct_load_ETC1( char * filename, int reuse_texture_ID, int flags );", "	( filename reuse_texture_ID flags -- )" );
	swigFunction( "c-function SOIL_direct_load_ETC1_from_memory SOIL_direct_load_ETC1_from_memory a n u n -- u", "FUNCTION: SOIL_direct_load_ETC1_from_memory ( buffer buffer_length reuse_texture_ID flags -- u )", "EXTERN: \"C\" int SOIL_direct_load_ETC1_from_memory( void * buffer, int buffer_length, int reuse_texture_ID, int flags );", "	( buffer buffer_length reuse_texture_ID flags -- )" );

	swigNewline();

	swigComment("----===< postfix >===-----\n");

	swigPrint( "end-c-library", "( none )", "( none )" );
	
	return 0;
} /* end of main */



