#!/bin/sh

#Authors: Bernd Paysan, Anton Ertl
#Copyright (C) 2008,2011,2012,2016,2017,2018,2019 Free Software Foundation, Inc.

#This file is part of Gforth.

#Gforth is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation, either version 3
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program. If not, see http://www.gnu.org/licenses/.

machine=amd64
VERSION=0.7.9_20200716
export HOSTPREFIX=""
test -z "$ENGINE" && ENGINE=./gforth
test -f "./kernl64l.fi" && KERNEL="./kernl64l.fi"
test -f "kernl64l.fi" && KERNEL="kernl64l.fi"
export libccdir="$PWD/lib/gforth/$VERSION/$machine/libcc-named/"
export libccnameddir="$libccdir"
if test -n "$C_INCLUDE_PATH"; then
    export C_INCLUDE_PATH="./include/gforth/$VERSION/$machine:./engine:$C_INCLUDE_PATH"
else
    export C_INCLUDE_PATH="./include/gforth/$VERSION/$machine:./engine"
fi
if test -f "$ENGINE" -a -f "$KERNEL"; then 
  $ENGINE --die-on-signal -i kernl64l.fi "$@" || printf "\e[31m*** Gforth kernel failed ***\e[0m\n" >&2
else
  "/usr/local/bin/gforth" -i "/usr/local/Cellar/gforth/0.7.3_2/lib/gforth/0.7.3/kernl64l.fi" "$@" || printf "\e[31m*** Gforth kernel failed ***\e[0m\n" >&2
fi
