#!/bin/sh

#Authors: Bernd Paysan, Anton Ertl
#Copyright (C) 2008,2011,2012,2014,2015,2016,2017,2018,2019 Free Software Foundation, Inc.

#This file is part of Gforth.

#Gforth is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation, either version 3
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program. If not, see http://www.gnu.org/licenses/.

machine=amd64
VERSION=0.7.9_20200716
DEST=$1
shift
export CROSS_PREFIX=
test -z "$ENGINE" && ENGINE=./gforth
test -f "gforth.fi" && KERNEL="gforth.fi"
export libccdir="$PWD/lib/gforth/$VERSION/$machine/libcc-named/"
export libccnameddir="$libccdir"
if test x".la" = "x.so" ; then
   export libccdir="$libccdir/.libs/"
fi
if test -n "$C_INCLUDE_PATH"; then
    export C_INCLUDE_PATH="./include/gforth/$VERSION/$machine:./engine:$C_INCLUDE_PATH"
else
    export C_INCLUDE_PATH="./include/gforth/$VERSION/$machine:./engine"
fi
EXTRAPATH="also c-lib :noname 2drop s\" $DEST\" ; is replace-rpath previous 0 warnings !@ get-current environment-wordlist set-current : os-type ( -- c-addr u ) s\" darwin\" ; set-current warnings !"
if test -f "$ENGINE" -a -f "$KERNEL"; then 
  $ENGINE -p ".:~+:.:$PWD" --die-on-signal -e "$EXTRAPATH" "$@"
else
  export includedir=`pwd`/include
  "/usr/local/bin/gforth" -i "/usr/local/Cellar/gforth/0.7.3_2/lib/gforth/0.7.3/kernl64l.fi" -p ".:~+:.:$PWD" exboot.fs startup.fs \
      -e "$EXTRAPATH" "$@"
fi
