#!/bin/sh

#Authors: Anton Ertl, Bernd Paysan
#Copyright (C) 2008,2011,2012,2016,2019 Free Software Foundation, Inc.

#This file is part of Gforth.

#Gforth is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation, either version 3
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program. If not, see http://www.gnu.org/licenses/.

test -z "$ENGINE" && ENGINE=./gforth
test -f "./kernl64l.fi" && KERNEL="./kernl64l.fi"
test -f "kernl64l.fi" && KERNEL="kernl64l.fi"
if test -f "$ENGINE" -a -f "$KERNEL"; then 
  path1="$1"
  path2="$2"
  shift; shift
#  set -x -v
  $ENGINE --die-on-signal -m64M -i kernl64l.fi $path1 $path2 exboot.fs startup.fs "$@"
else
  "/usr/local/bin/gforth" -i "/usr/local/Cellar/gforth/0.7.3_2/lib/gforth/0.7.3/gforth.fi" -m64M "$@"
fi
